"""Local web front-end for Shia-Aalim (FastAPI).

This wraps the *same* :class:`~shia_aalim.generation.answer.AnswerGenerator` and
:class:`~shia_aalim.generation.lecture.LectureGenerator` that ``scripts/demo.py``
uses in a tiny HTTP API plus a single self-contained HTML page, so the assistant
can be used in a browser instead of the terminal.

Nothing here weakens the charter guarantees. The web layer only *presents* what
the pipeline produces: answers are generated by the exact same grounded
retrieval + verification path, every claim still carries its citation and
confidence, and the grounding firewall still withholds anything it can't verify.
The browser just renders that structured output.

    pip install -e ".[web]"          # fastapi + uvicorn
    python -m shia_aalim.web         # serve on http://127.0.0.1:8000

FastAPI/uvicorn are optional extras; importing this module (or calling
:func:`create_app`) without them raises a clear install hint rather than a bare
``ImportError``. The corpus is loaded once at startup; each configured embedder's
index is built lazily on first use (the default is built at startup so the
corpus is validated), so the front-end runs anywhere the CLI does and a
switchable semantic embedder that isn't reachable degrades to a clear message
rather than crashing the server.
"""

from __future__ import annotations

import argparse
import sys
from dataclasses import dataclass, field
from pathlib import Path
from typing import Optional

from .generation.answer import AnswerGenerator
from .generation.decompose import make_decomposer
from .generation.lecture import Lecture, LectureGenerator
from .generation.synthesizer import make_synthesizer
from .grounding.entailment import make_judge
from .ingestion.loaders import iter_knowledge_dir
from .models import Answer, Document
from .research_loop import build_index
from .retrieval.embeddings import make_embedder
from .sources import load_registry_ids

ROOT = Path(__file__).resolve().parent.parent.parent
DEFAULT_KNOWLEDGE_DIR = ROOT / "data" / "knowledge"
DEFAULT_REGISTRY = ROOT / "data" / "sources" / "registry.yaml"

_FASTAPI_HINT = (
    "The web front-end needs FastAPI and uvicorn, which are optional extras.\n"
    "Install them with:\n\n    pip install -e \".[web]\"\n\n"
    "(or: pip install fastapi uvicorn). The CLI — scripts/demo.py — needs no extras."
)

# Request body models live at *module* level (not inside create_app): with
# ``from __future__ import annotations`` in effect, FastAPI resolves endpoint
# annotations against the function's module globals, so a locally-scoped model
# would silently be misread as a query parameter. Pydantic ships with FastAPI;
# guard the import so merely importing this module never hard-requires the extra.
try:
    from pydantic import BaseModel as _BaseModel

    class AskBody(_BaseModel):
        question: str = ""
        k: Optional[int] = None
        embedder: Optional[str] = None  # which index to query; None = default

    class LectureBody(_BaseModel):
        topic: str = ""
        depth: Optional[int] = None
        embedder: Optional[str] = None

except ImportError:  # pragma: no cover - only without the web extra
    AskBody = None  # type: ignore
    LectureBody = None  # type: ignore


class EmbedderUnavailable(RuntimeError):
    """A configured embedder could not be built (e.g. semantic model unreachable)."""


@dataclass
class AppConfig:
    """How to build the retrieval + generation stack behind the web app."""

    knowledge_dir: Path = DEFAULT_KNOWLEDGE_DIR
    registry_path: Path = DEFAULT_REGISTRY
    embedders: list[str] = field(default_factory=lambda: ["tfidf"])
    synthesize: str = "none"
    judge: str = "lexical"
    decompose: str = "none"
    default_k: int = 6

    @property
    def default_embedder(self) -> str:
        return self.embedders[0]


@dataclass
class Engine:
    """The two generators bound to one embedder's index."""

    answers: AnswerGenerator
    lectures: LectureGenerator


class Stack:
    """Holds the corpus and builds a per-embedder :class:`Engine` on demand.

    Each embedder needs its *own* index (the vectors differ), so switching
    embedders means querying a different retriever. Indexes are built lazily and
    cached: the default embedder is built eagerly (validating the corpus at
    startup); any additional configured embedder is built the first time it is
    requested, and a build failure (e.g. an unreachable semantic model) is cached
    and surfaced as :class:`EmbedderUnavailable` rather than retried or crashed.
    """

    def __init__(
        self, docs: list[Document], config: AppConfig, known: Optional[set[str]] = None
    ) -> None:
        self.docs = docs
        self.config = config
        self.known = known
        # Providers are index-independent, so build them once and share.
        self._synthesizer = make_synthesizer(config.synthesize)
        self._judge = make_judge(config.judge)
        self._decomposer = make_decomposer(config.decompose)
        self._engines: dict[str, Engine] = {}
        self._errors: dict[str, str] = {}

    @property
    def n_documents(self) -> int:
        return len(self.docs)

    @property
    def embedders(self) -> list[str]:
        return list(self.config.embedders)

    @property
    def default_embedder(self) -> str:
        return self.config.default_embedder

    def embedder_state(self, spec: str) -> str:
        """``ready`` (built), ``failed`` (build errored), or ``lazy`` (not yet built)."""
        if spec in self._engines:
            return "ready"
        if spec in self._errors:
            return "failed"
        return "lazy"

    def error_for(self, spec: str) -> Optional[str]:
        return self._errors.get(spec)

    def engine(self, spec: Optional[str] = None) -> Engine:
        """Return the Engine for ``spec`` (default embedder if None), building it once."""
        spec = spec or self.default_embedder
        if spec not in self.config.embedders:
            raise EmbedderUnavailable(
                f"Embedder {spec!r} is not enabled. Available: "
                + ", ".join(self.config.embedders)
            )
        if spec in self._engines:
            return self._engines[spec]
        if spec in self._errors:
            raise EmbedderUnavailable(self._errors[spec])
        try:
            retriever = build_index(self.docs, embedder=make_embedder(spec))
        except Exception as exc:  # noqa: BLE001 - report, don't crash the server
            self._errors[spec] = str(exc)
            raise EmbedderUnavailable(str(exc)) from exc
        engine = Engine(
            answers=AnswerGenerator(
                retriever,
                synthesizer=self._synthesizer,
                known_source_ids=self.known,
                judge=self._judge,
                decomposer=self._decomposer,
            ),
            lectures=LectureGenerator(
                retriever, synthesizer=self._synthesizer, judge=self._judge
            ),
        )
        self._engines[spec] = engine
        return engine


def build_stack(config: Optional[AppConfig] = None) -> Stack:
    """Load the corpus and prepare the generators (default index built eagerly).

    Pure pipeline code — no web dependency — so it is unit-testable on its own
    and reused by both the API and any embedded use.
    """
    config = config or AppConfig()
    docs = list(iter_knowledge_dir(config.knowledge_dir))
    if not docs:
        raise RuntimeError(
            f"No documents found under {config.knowledge_dir}. Build the corpus "
            "first (python scripts/ingest.py) or point --knowledge-dir at a "
            "directory of .jsonl knowledge files."
        )
    known = _load_known_ids(config.registry_path)
    stack = Stack(docs, config, known)
    stack.engine(config.default_embedder)  # eager: validate corpus + default index
    return stack


def _load_known_ids(registry_path: Path) -> Optional[set[str]]:
    try:
        return load_registry_ids(registry_path)
    except FileNotFoundError:
        return None


# ---------------------------------------------------------------------------
# JSON payload builders (structured, so the browser can render badges itself)
# ---------------------------------------------------------------------------


def answer_to_payload(answer: Answer, markdown: str) -> dict:
    return {"answer": answer.to_dict(), "markdown": markdown}


def lecture_to_payload(lecture: Lecture) -> dict:
    return {
        "topic": lecture.topic,
        "generated_on": lecture.generated_on,
        "sections": [
            {
                "title": s.title,
                "body": s.body,
                "synthesized": s.synthesized,
                "note": s.note or "",
                "evidence": [
                    {
                        "text": r.document.text.strip(),
                        "reference": r.document.citation.reference_string(),
                        "confidence": r.document.confidence.value,
                        "evidence_type": r.document.evidence_type.value,
                        "translation": r.document.citation.translation,
                    }
                    for r in s.evidence
                ],
            }
            for s in lecture.sections
        ],
        "markdown": lecture.to_markdown(),
    }


# ---------------------------------------------------------------------------
# FastAPI app
# ---------------------------------------------------------------------------


def create_app(config: Optional[AppConfig] = None, *, stack: Optional[Stack] = None):
    """Build the FastAPI application.

    ``stack`` lets tests inject a pre-built (small-corpus) stack; otherwise it is
    built from ``config`` at creation time. Raises a clear ImportError with an
    install hint if FastAPI isn't available.
    """
    try:
        from fastapi import FastAPI
        from fastapi.responses import HTMLResponse, JSONResponse
    except ImportError as exc:  # pragma: no cover - exercised only without the extra
        raise ImportError(_FASTAPI_HINT) from exc

    stack = stack or build_stack(config)

    app = FastAPI(
        title="Shia-Aalim",
        description="Evidence-first Twelver Shia research & lecture assistant. "
        "No citation = not a fact.",
        version="0.1.0",
    )
    app.state.stack = stack

    @app.get("/", response_class=HTMLResponse)
    async def index() -> str:
        return INDEX_HTML

    @app.get("/api/status")
    async def status() -> dict:
        cfg = stack.config
        return {
            "documents": stack.n_documents,
            "embedders": [
                {"spec": spec, "state": stack.embedder_state(spec),
                 "default": spec == stack.default_embedder}
                for spec in stack.embedders
            ],
            "default_embedder": stack.default_embedder,
            "synthesizer": cfg.synthesize,
            "judge": cfg.judge,
            "decomposer": cfg.decompose,
            "default_k": cfg.default_k,
        }

    @app.post("/api/answer")
    async def api_answer(body: AskBody):
        question = (body.question or "").strip()
        if not question:
            return JSONResponse({"error": "question is required"}, status_code=400)
        try:
            engine = stack.engine(body.embedder)
        except EmbedderUnavailable as exc:
            return JSONResponse({"error": _embedder_error(body.embedder, exc)}, status_code=503)
        k = _clamp_int(body.k, default=stack.config.default_k, lo=1, hi=25)
        answer = engine.answers.answer(question, k=k)
        markdown = engine.answers.format_markdown(answer)
        payload = answer_to_payload(answer, markdown)
        payload["embedder"] = body.embedder or stack.default_embedder
        return payload

    @app.post("/api/lecture")
    async def api_lecture(body: LectureBody):
        topic = (body.topic or "").strip()
        if not topic:
            return JSONResponse({"error": "topic is required"}, status_code=400)
        try:
            engine = stack.engine(body.embedder)
        except EmbedderUnavailable as exc:
            return JSONResponse({"error": _embedder_error(body.embedder, exc)}, status_code=503)
        depth = _clamp_int(body.depth, default=4, lo=1, hi=10)
        lecture = engine.lectures.generate(topic, depth=depth)
        payload = lecture_to_payload(lecture)
        payload["embedder"] = body.embedder or stack.default_embedder
        return payload

    return app


def _embedder_error(spec: Optional[str], exc: Exception) -> str:
    return (
        f"The '{spec}' embedder is not available in this environment: {exc}. "
        "Semantic models (st:…) need the [embeddings] extra and a reachable "
        "model; switch back to the tfidf index."
    )


def _clamp_int(value, *, default: int, lo: int, hi: int) -> int:
    try:
        n = int(value)
    except (TypeError, ValueError):
        return default
    return max(lo, min(hi, n))


# ---------------------------------------------------------------------------
# Single-page UI — self-contained (no external assets), so it works offline.
# ---------------------------------------------------------------------------

INDEX_HTML = r"""<!doctype html>
<html lang="en">
<head>
<meta charset="utf-8">
<meta name="viewport" content="width=device-width, initial-scale=1">
<title>Shia-Aalim — evidence-first research assistant</title>
<style>
  :root {
    --bg: #0f1114; --panel: #171a1f; --panel2: #1e232a; --line: #2a3038;
    --ink: #e7ecf2; --muted: #93a1b0; --accent: #3f8cff; --accent2: #2b6fd6;
    --high: #2ea043; --medium: #d29922; --low: #db6d28; --unverified: #6e7681;
    --quran: #7c5cff; --hadith: #2ea3a3; --tafsir: #c46fd6;
    --historical: #d2792a; --scholarly: #4b8ef0;
  }
  @media (prefers-color-scheme: light) {
    :root {
      --bg: #f5f7fa; --panel: #ffffff; --panel2: #eef1f5; --line: #dde3ea;
      --ink: #10151c; --muted: #5a6672; --accent: #1f6feb; --accent2: #1a5fd0;
    }
  }
  * { box-sizing: border-box; }
  body {
    margin: 0; background: var(--bg); color: var(--ink);
    font: 15px/1.55 -apple-system, BlinkMacSystemFont, "Segoe UI", Roboto, Helvetica, Arial, sans-serif;
  }
  header {
    padding: 20px 22px; border-bottom: 1px solid var(--line);
    background: var(--panel); position: sticky; top: 0; z-index: 5;
  }
  header h1 { margin: 0; font-size: 20px; letter-spacing: .2px; }
  header .tag { color: var(--muted); font-size: 13px; margin-top: 3px; }
  header .tag b { color: var(--accent); }
  main { max-width: 900px; margin: 0 auto; padding: 22px 18px 80px; }
  .tabs { display: flex; gap: 8px; margin-bottom: 18px; }
  .tab {
    padding: 8px 16px; border: 1px solid var(--line); border-radius: 999px;
    background: var(--panel); color: var(--muted); cursor: pointer; font-size: 14px;
  }
  .tab.active { background: var(--accent); border-color: var(--accent); color: #fff; }
  .row { display: flex; gap: 10px; flex-wrap: wrap; }
  input[type=text] {
    flex: 1 1 320px; padding: 12px 14px; border-radius: 10px;
    border: 1px solid var(--line); background: var(--panel); color: var(--ink); font-size: 15px;
  }
  input[type=number] {
    width: 88px; padding: 12px 10px; border-radius: 10px;
    border: 1px solid var(--line); background: var(--panel); color: var(--ink); font-size: 15px;
  }
  button.go {
    padding: 12px 20px; border: 0; border-radius: 10px; cursor: pointer;
    background: var(--accent); color: #fff; font-size: 15px; font-weight: 600;
  }
  button.go:disabled { opacity: .5; cursor: default; }
  label.fld { display: flex; flex-direction: column; gap: 4px; font-size: 12px; color: var(--muted); }
  .hint { color: var(--muted); font-size: 13px; margin: 10px 2px 0; }
  .status { color: var(--muted); font-size: 12.5px; margin-top: 14px; }
  .result { margin-top: 22px; }
  .qtitle { font-size: 18px; font-weight: 650; margin: 0 0 6px; }
  .subq { color: var(--muted); font-size: 13px; margin: 0 0 14px; }
  .summary {
    background: var(--panel2); border: 1px solid var(--line); border-left: 3px solid var(--accent);
    padding: 12px 14px; border-radius: 8px; margin: 0 0 18px; white-space: pre-wrap;
  }
  .summary .lbl { color: var(--muted); font-size: 12px; margin-bottom: 6px; }
  .evhead { font-size: 13px; text-transform: uppercase; letter-spacing: .6px; color: var(--muted); margin: 18px 0 8px; }
  .ev {
    background: var(--panel); border: 1px solid var(--line); border-radius: 10px;
    padding: 12px 14px; margin-bottom: 10px;
  }
  .ev .txt { margin: 0 0 8px; }
  .ev .ar { direction: rtl; text-align: right; font-size: 17px; line-height: 1.9; }
  .badges { display: flex; gap: 6px; flex-wrap: wrap; align-items: center; }
  .badge {
    font-size: 11px; font-weight: 700; text-transform: uppercase; letter-spacing: .4px;
    padding: 2px 8px; border-radius: 999px; color: #fff;
  }
  .ref { color: var(--muted); font-size: 12.5px; margin-left: auto; font-variant-numeric: tabular-nums; }
  .b-high { background: var(--high); } .b-medium { background: var(--medium); }
  .b-low { background: var(--low); } .b-unverified { background: var(--unverified); }
  .t-quran { background: var(--quran); } .t-hadith { background: var(--hadith); }
  .t-tafsir { background: var(--tafsir); } .t-historical { background: var(--historical); }
  .t-scholarly_opinion { background: var(--scholarly); } .t-biographical { background: #8a7a5c; }
  .t-linguistic { background: #5c8a7a; } .t-historical { background: var(--historical); }
  .caveats { margin-top: 20px; border-top: 1px dashed var(--line); padding-top: 14px; }
  .caveats .lbl { color: var(--low); font-size: 12px; text-transform: uppercase; letter-spacing: .5px; }
  .caveats ul { margin: 8px 0 0; padding-left: 18px; }
  .caveats li { color: var(--muted); font-size: 13px; margin-bottom: 5px; }
  .sec { margin-bottom: 22px; }
  .sec h3 { margin: 0 0 4px; font-size: 16px; }
  .sec .note { color: var(--muted); font-size: 13px; font-style: italic; margin: 2px 0 8px; }
  .sec .body { white-space: pre-wrap; margin: 6px 0 10px; }
  .synth { color: var(--high); font-size: 12px; font-weight: 600; }
  .empty { color: var(--muted); padding: 20px 0; }
  .spinner { color: var(--muted); padding: 20px 0; }
  footer { color: var(--muted); font-size: 12px; text-align: center; padding: 30px 0 10px; }
  code { background: var(--panel2); padding: 1px 5px; border-radius: 4px; font-size: 12.5px; }
  select {
    padding: 11px 12px; border-radius: 10px; border: 1px solid var(--line);
    background: var(--panel); color: var(--ink); font-size: 14px;
  }
  select:disabled { opacity: .6; }
  .toolbar { display: flex; gap: 8px; margin: 4px 0 14px; }
  .toolbar.hidden { display: none; }
  button.mini {
    padding: 6px 12px; border: 1px solid var(--line); border-radius: 8px; cursor: pointer;
    background: var(--panel); color: var(--ink); font-size: 12.5px;
  }
  button.mini:hover { border-color: var(--accent); color: var(--accent); }
  .idxrow { display: flex; align-items: center; gap: 8px; margin-bottom: 14px; color: var(--muted); font-size: 13px; }
  .idxnote { font-size: 12px; color: var(--muted); }
</style>
</head>
<body>
<header>
  <h1>Shia-Aalim</h1>
  <div class="tag">Evidence-first Twelver (Ithnā ʿAsharī) research &amp; lecture assistant · <b>No citation = not a fact.</b></div>
</header>
<main>
  <div class="tabs">
    <div class="tab active" data-tab="ask" onclick="switchTab('ask')">Ask a question</div>
    <div class="tab" data-tab="lecture" onclick="switchTab('lecture')">Prepare a lecture</div>
  </div>

  <div class="idxrow">
    <label for="embedder">Retrieval index</label>
    <select id="embedder" disabled onchange="onEmbedderChange()"><option>loading…</option></select>
    <span class="idxnote" id="idxnote"></span>
  </div>

  <section id="pane-ask">
    <div class="row">
      <input type="text" id="q" placeholder="e.g. What does the Qur'an say about justice?" onkeydown="if(event.key==='Enter')ask()">
      <label class="fld">evidence<input type="number" id="k" value="6" min="1" max="25"></label>
      <button class="go" id="askBtn" onclick="ask()">Ask</button>
    </div>
    <div class="hint">Every answer is grounded in retrieved, cited passages. Weak or disputed evidence is flagged, never hidden.</div>
    <div class="toolbar hidden" id="askTools">
      <button class="mini" onclick="copyMd('ask')">⧉ Copy Markdown</button>
      <button class="mini" onclick="downloadMd('ask')">⭳ Download .md</button>
    </div>
    <div class="result" id="askResult"></div>
  </section>

  <section id="pane-lecture" style="display:none">
    <div class="row">
      <input type="text" id="topic" placeholder="e.g. The patience (ṣabr) of Imam Husayn (a)" onkeydown="if(event.key==='Enter')lecture()">
      <label class="fld">depth<input type="number" id="depth" value="4" min="1" max="10"></label>
      <button class="go" id="lecBtn" onclick="lecture()">Build outline</button>
    </div>
    <div class="hint">Builds the 11-section majlis/khutbah framework. Evidence sections are filled from cited passages; narrative sections are LLM-written only when a synthesizer is enabled and the prose verifies against the evidence.</div>
    <div class="toolbar hidden" id="lecTools">
      <button class="mini" onclick="copyMd('lec')">⧉ Copy Markdown</button>
      <button class="mini" onclick="downloadMd('lec')">⭳ Download .md</button>
    </div>
    <div class="result" id="lecResult"></div>
  </section>

  <div class="status" id="status">Loading corpus status…</div>
</main>
<footer>Shia-Aalim · answers are aids to research, not a substitute for a qualified scholar (marjaʿ). Verify every citation against the primary source.</footer>

<script>
function esc(s){ return (s==null?'':String(s)).replace(/[&<>"']/g, c => ({'&':'&amp;','<':'&lt;','>':'&gt;','"':'&quot;',"'":'&#39;'}[c])); }
function isArabic(s){ return /[؀-ۿ]/.test(s||''); }

function switchTab(name){
  document.querySelectorAll('.tab').forEach(t => t.classList.toggle('active', t.dataset.tab===name));
  document.getElementById('pane-ask').style.display = name==='ask' ? '' : 'none';
  document.getElementById('pane-lecture').style.display = name==='lecture' ? '' : 'none';
}

function badge(kind, cls, label){ return '<span class="badge '+cls+'-'+kind+'">'+esc(label)+'</span>'; }

function evidenceBlock(ev){
  var conf = ev.confidence || 'unverified';
  var type = ev.evidence_type || '';
  var txt = ev.text || (ev.citation && ev.citation.arabic_text) || '';
  var ref = ev.reference || '';
  var cls = isArabic(txt) ? 'txt ar' : 'txt';
  var trans = ev.translation ? '<p class="txt" style="color:var(--muted);font-size:13.5px">'+esc(ev.translation)+'</p>' : '';
  return '<div class="ev"><p class="'+cls+'">'+esc(txt)+'</p>'+trans+
    '<div class="badges">'+badge(type,'t',type.replace(/_/g,' '))+badge(conf,'b',conf)+
    '<span class="ref">'+esc(ref)+'</span></div></div>';
}

function claimToEvidence(c){
  var cit = (c.citations && c.citations[0]) || {};
  return {
    text: c.statement,
    reference: refString(cit),
    confidence: c.confidence,
    evidence_type: c.evidence_type,
    translation: cit.translation || null,
  };
}
function refString(cit){
  if(!cit) return '';
  if(cit.evidence_type==='quran' && cit.surah) return "Qur'an "+cit.surah+':'+cit.ayah;
  var p=[cit.source_id];
  if(cit.volume) p.push('v'+cit.volume);
  if(cit.page) p.push('p.'+cit.page);
  if(cit.hadith_number) p.push('h.'+cit.hadith_number);
  if(cit.chapter) p.push('ch.'+cit.chapter);
  return p.filter(Boolean).join(', ');
}

// Last-rendered Markdown per tab, for the copy / download buttons.
var lastMd = { ask: {text:'', name:'answer'}, lec: {text:'', name:'lecture'} };
function slug(s){ return (s||'shia-aalim').toLowerCase().replace(/[^a-z0-9]+/g,'-').replace(/^-|-$/g,'').slice(0,60) || 'shia-aalim'; }
function selectedEmbedder(){ var el = document.getElementById('embedder'); return el && el.value ? el.value : null; }
function showTools(tab){ document.getElementById(tab+'Tools').classList.remove('hidden'); }
function hideTools(tab){ document.getElementById(tab+'Tools').classList.add('hidden'); }

async function copyMd(tab){
  var md = lastMd[tab].text; if(!md) return;
  try { await navigator.clipboard.writeText(md); flash(tab, 'Copied ✓'); }
  catch(e){
    var ta = document.createElement('textarea'); ta.value = md; document.body.appendChild(ta);
    ta.select(); try { document.execCommand('copy'); flash(tab,'Copied ✓'); } catch(_){}
    document.body.removeChild(ta);
  }
}
function downloadMd(tab){
  var md = lastMd[tab].text; if(!md) return;
  var blob = new Blob([md], {type:'text/markdown;charset=utf-8'});
  var url = URL.createObjectURL(blob);
  var a = document.createElement('a');
  a.href = url; a.download = slug(lastMd[tab].name) + '.md';
  document.body.appendChild(a); a.click(); document.body.removeChild(a);
  URL.revokeObjectURL(url);
}
function flash(tab, msg){
  var btn = document.querySelector('#'+tab+'Tools button'); if(!btn) return;
  var old = btn.textContent; btn.textContent = msg;
  setTimeout(function(){ btn.textContent = old; }, 1200);
}

async function ask(){
  var q = document.getElementById('q').value.trim();
  if(!q) return;
  var k = document.getElementById('k').value;
  var box = document.getElementById('askResult');
  var btn = document.getElementById('askBtn');
  btn.disabled = true; hideTools('ask'); box.innerHTML = '<div class="spinner">Searching the corpus…</div>';
  try {
    var res = await fetch('/api/answer', {method:'POST', headers:{'Content-Type':'application/json'}, body: JSON.stringify({question:q, k:Number(k), embedder:selectedEmbedder()})});
    var data = await res.json();
    if(data.error){ box.innerHTML = '<div class="empty">'+esc(data.error)+'</div>'; return; }
    renderAnswer(box, data.answer);
    lastMd.ask = { text: data.markdown || '', name: data.answer.question };
    showTools('ask');
  } catch(e){ box.innerHTML = '<div class="empty">Request failed: '+esc(e.message)+'</div>'; }
  finally { btn.disabled = false; }
}

function renderAnswer(box, a){
  var h = '<div class="qtitle">'+esc(a.question)+'</div>';
  if(a.sub_questions && a.sub_questions.length)
    h += '<p class="subq">Decomposed into: '+a.sub_questions.map(esc).join(' · ')+'</p>';
  if(a.summary)
    h += '<div class="summary"><div class="lbl">Synthesized answer — LLM prose, verified against the evidence below</div>'+esc(a.summary)+'</div>';
  if(!a.claims || !a.claims.length){
    h += '<div class="empty">No sufficiently-relevant evidence was found in the knowledge base for this question.</div>';
  } else {
    h += '<div class="evhead">Evidence ('+a.claims.length+')</div>';
    h += a.claims.map(c => evidenceBlock(claimToEvidence(c))).join('');
  }
  if(a.caveats && a.caveats.length)
    h += '<div class="caveats"><div class="lbl">Caveats</div><ul>'+a.caveats.map(c=>'<li>'+esc(c)+'</li>').join('')+'</ul></div>';
  box.innerHTML = h;
}

async function lecture(){
  var t = document.getElementById('topic').value.trim();
  if(!t) return;
  var depth = document.getElementById('depth').value;
  var box = document.getElementById('lecResult');
  var btn = document.getElementById('lecBtn');
  btn.disabled = true; hideTools('lec'); box.innerHTML = '<div class="spinner">Building the outline…</div>';
  try {
    var res = await fetch('/api/lecture', {method:'POST', headers:{'Content-Type':'application/json'}, body: JSON.stringify({topic:t, depth:Number(depth), embedder:selectedEmbedder()})});
    var data = await res.json();
    if(data.error){ box.innerHTML = '<div class="empty">'+esc(data.error)+'</div>'; return; }
    renderLecture(box, data);
    lastMd.lec = { text: data.markdown || '', name: data.topic };
    showTools('lec');
  } catch(e){ box.innerHTML = '<div class="empty">Request failed: '+esc(e.message)+'</div>'; }
  finally { btn.disabled = false; }
}

function renderLecture(box, L){
  var h = '<div class="qtitle">'+esc(L.topic)+'</div><p class="subq">Outline generated '+esc(L.generated_on)+'. Verify every citation before delivery.</p>';
  h += L.sections.map(s => {
    var out = '<div class="sec"><h3>'+esc(s.title)+(s.synthesized?' <span class="synth">✓ synthesized &amp; verified</span>':'')+'</h3>';
    if(s.body) out += '<div class="body">'+esc(s.body)+'</div>';
    out += s.evidence.map(evidenceBlock).join('');
    if(s.note) out += '<div class="note">Lecturer note: '+esc(s.note)+'</div>';
    return out + '</div>';
  }).join('');
  box.innerHTML = h;
}

function stateTag(st){ return st==='ready' ? '' : st==='failed' ? ' (unavailable)' : ' — builds on first use'; }

function onEmbedderChange(){
  var el = document.getElementById('embedder');
  var st = el.options[el.selectedIndex] ? el.options[el.selectedIndex].dataset.state : 'ready';
  document.getElementById('idxnote').textContent =
    st==='lazy' ? 'This index will be built the first time you query it.' :
    st==='failed' ? 'This index failed to build in this environment; queries will report the reason.' : '';
}

fetch('/api/status').then(r=>r.json()).then(s=>{
  var sel = document.getElementById('embedder');
  sel.innerHTML = (s.embedders||[]).map(function(e){
    return '<option value="'+esc(e.spec)+'" data-state="'+esc(e.state)+'"'+(e.default?' selected':'')+'>'+
      esc(e.spec)+stateTag(e.state)+'</option>';
  }).join('');
  sel.disabled = (s.embedders||[]).length < 2;   // nothing to switch between
  onEmbedderChange();
  document.getElementById('status').innerHTML =
    'Corpus: <b>'+s.documents.toLocaleString()+'</b> documents · default index <code>'+esc(s.default_embedder)+
    '</code> · synthesizer <code>'+esc(s.synthesizer)+'</code> · judge <code>'+esc(s.judge)+'</code>';
}).catch(()=>{ document.getElementById('status').textContent = ''; });
</script>
</body>
</html>
"""


# ---------------------------------------------------------------------------
# CLI
# ---------------------------------------------------------------------------


def main(argv: Optional[list[str]] = None) -> int:
    parser = argparse.ArgumentParser(
        description="Serve the Shia-Aalim web front-end (FastAPI + uvicorn).",
        formatter_class=argparse.RawDescriptionHelpFormatter,
    )
    parser.add_argument("--host", default="127.0.0.1")
    parser.add_argument("--port", type=int, default=8000)
    parser.add_argument("--knowledge-dir", default=str(DEFAULT_KNOWLEDGE_DIR))
    parser.add_argument("--registry", default=str(DEFAULT_REGISTRY))
    parser.add_argument(
        "--embedder", default="tfidf",
        help="one or a comma-separated list to offer as a UI toggle; the first is "
        "the default (e.g. 'tfidf' or 'tfidf,st:BAAI/bge-m3'). tfidf | hashing | st:<model>",
    )
    parser.add_argument("--synthesize", default="none", help="none | mock | claude:<model>")
    parser.add_argument("--judge", default="lexical", help="lexical | mock | claude:<model>")
    parser.add_argument("--decompose", default="none", help="none | rule | claude:<model>")
    parser.add_argument("--k", type=int, default=6, help="default evidence count per answer")
    args = parser.parse_args(argv)

    try:
        import uvicorn
    except ImportError:
        print(_FASTAPI_HINT, file=sys.stderr)
        return 1

    embedders = [s.strip() for s in args.embedder.split(",") if s.strip()] or ["tfidf"]
    config = AppConfig(
        knowledge_dir=Path(args.knowledge_dir),
        registry_path=Path(args.registry),
        embedders=embedders,
        synthesize=args.synthesize,
        judge=args.judge,
        decompose=args.decompose,
        default_k=args.k,
    )
    print(f"Loading corpus from {config.knowledge_dir} …", file=sys.stderr)
    app = create_app(config)
    n = app.state.stack.n_documents
    extra = [e for e in embedders[1:]]
    switch = f" (+{', '.join(extra)} on first use)" if extra else ""
    print(
        f"Loaded {n:,} documents; default index '{config.default_embedder}' ready{switch}. "
        f"Serving Shia-Aalim on http://{args.host}:{args.port}",
        file=sys.stderr,
    )
    uvicorn.run(app, host=args.host, port=args.port)
    return 0


if __name__ == "__main__":
    raise SystemExit(main())
