"""Local web front-end for Shia-Aalim (FastAPI).

This wraps the *same* :class:`~shia_aalim.generation.answer.AnswerGenerator` and
:class:`~shia_aalim.generation.lecture.LectureGenerator` that ``scripts/demo.py``
uses in a tiny HTTP API plus a single self-contained HTML page, so the assistant
can be used in a browser instead of the terminal.

Nothing here weakens the charter guarantees. The web layer only *presents* what
the pipeline produces: answers are generated by the exact same grounded
retrieval + verification path, every claim still carries its citation and
confidence, and the grounding firewall still withholds anything it can't verify.
The browser just renders that structured output.

    pip install -e ".[web]"          # fastapi + uvicorn
    python -m shia_aalim.web         # serve on http://127.0.0.1:8000

FastAPI/uvicorn are optional extras; importing this module (or calling
:func:`create_app`) without them raises a clear install hint rather than a bare
``ImportError``. The corpus is loaded once at startup; each configured embedder's
index is built lazily on first use (the default is built at startup so the
corpus is validated), so the front-end runs anywhere the CLI does and a
switchable semantic embedder that isn't reachable degrades to a clear message
rather than crashing the server.
"""

from __future__ import annotations

import argparse
import os
import sys
from dataclasses import dataclass, field
from pathlib import Path
from typing import Optional

from .generation.answer import AnswerGenerator
from .generation.crossref import CrossReferencer, CrossRefResult, build_verse_index
from .generation.decompose import make_decomposer
from .generation.lecture import Lecture, LectureGenerator
from .generation.refine import make_refiner
from .generation.synthesizer import make_synthesizer
from .grounding.entailment import make_judge
from .ingestion.loaders import iter_knowledge_dir
from .models import Answer, ConfidenceLevel, Document, EvidenceType, Source
from .research_loop import build_index
from .retrieval.embeddings import make_embedder
from .retrieval.index import build_persistent_index
from .retrieval.retriever import Retriever
from .rijal import NarratorIndex, extract_chain, parse_grade_source
from .sources import load_registry_ids, load_sources

ROOT = Path(__file__).resolve().parent.parent.parent
DEFAULT_KNOWLEDGE_DIR = ROOT / "data" / "knowledge"
DEFAULT_REGISTRY = ROOT / "data" / "sources" / "registry.yaml"

_FASTAPI_HINT = (
    "The web front-end needs FastAPI and uvicorn, which are optional extras.\n"
    "Install them with:\n\n    pip install -e \".[web]\"\n\n"
    "(or: pip install fastapi uvicorn). The CLI — scripts/demo.py — needs no extras."
)

# Request body models live at *module* level (not inside create_app): with
# ``from __future__ import annotations`` in effect, FastAPI resolves endpoint
# annotations against the function's module globals, so a locally-scoped model
# would silently be misread as a query parameter. Pydantic ships with FastAPI;
# guard the import so merely importing this module never hard-requires the extra.
try:
    from pydantic import BaseModel as _BaseModel

    class AskBody(_BaseModel):
        question: str = ""
        k: Optional[int] = None
        embedder: Optional[str] = None  # which index to query; None = default
        evidence_types: Optional[list[str]] = None  # restrict to these types; None = all
        source_ids: Optional[list[str]] = None  # restrict to these books; None/[] = all
        min_confidence: Optional[str] = None  # floor: unverified|low|medium|high
        answer_language: Optional[str] = None  # output language: en | ur | ar

    class LectureBody(_BaseModel):
        topic: str = ""
        depth: Optional[int] = None
        embedder: Optional[str] = None
        source_ids: Optional[list[str]] = None

    class CompareBody(_BaseModel):
        question: str = ""
        sources: Optional[list[str]] = None  # books to compare, one column each
        k: Optional[int] = None
        embedder: Optional[str] = None
        evidence_types: Optional[list[str]] = None
        min_confidence: Optional[str] = None

    class CrossrefBody(_BaseModel):
        surah: Optional[int] = None
        ayah: Optional[int] = None
        k: Optional[int] = None
        embedder: Optional[str] = None

    class NarratorBody(_BaseModel):
        name: str = ""
        limit: Optional[int] = None

except ImportError:  # pragma: no cover - only without the web extra
    AskBody = None  # type: ignore
    LectureBody = None  # type: ignore
    CompareBody = None  # type: ignore
    CrossrefBody = None  # type: ignore
    NarratorBody = None  # type: ignore


# The compare view runs one retrieval per selected book; cap the fan-out.
MAX_COMPARE_SOURCES = 6


class EmbedderUnavailable(RuntimeError):
    """A configured embedder could not be built (e.g. semantic model unreachable)."""


@dataclass
class AppConfig:
    """How to build the retrieval + generation stack behind the web app."""

    knowledge_dir: Path = DEFAULT_KNOWLEDGE_DIR
    registry_path: Path = DEFAULT_REGISTRY
    embedders: list[str] = field(default_factory=lambda: ["tfidf"])
    synthesize: str = "none"
    judge: str = "lexical"
    decompose: str = "none"
    refine: str = "none"
    default_k: int = 6
    # When set, each embedder's vectors are cached here (embed once, reuse across
    # restarts). Essential for semantic embedders — the corpus is embedded at
    # build time (scripts/warm_index.py) and loaded instantly at runtime.
    cache_dir: Optional[Path] = None

    @property
    def default_embedder(self) -> str:
        return self.embedders[0]


@dataclass
class Engine:
    """The two generators bound to one embedder's index."""

    answers: AnswerGenerator
    lectures: LectureGenerator


class Stack:
    """Holds the corpus and builds a per-embedder :class:`Engine` on demand.

    Each embedder needs its *own* index (the vectors differ), so switching
    embedders means querying a different retriever. Indexes are built lazily and
    cached: the default embedder is built eagerly (validating the corpus at
    startup); any additional configured embedder is built the first time it is
    requested, and a build failure (e.g. an unreachable semantic model) is cached
    and surfaced as :class:`EmbedderUnavailable` rather than retried or crashed.
    """

    def __init__(
        self,
        docs: list[Document],
        config: AppConfig,
        known: Optional[set[str]] = None,
        sources_meta: Optional[dict[str, Source]] = None,
    ) -> None:
        self.docs = docs
        self.config = config
        self.known = known
        self.sources_meta = sources_meta or {}
        self.provider_notes: list[str] = []
        # Providers are index-independent, so build them once and share. LLM-backed
        # ones are guarded: a missing/invalid API key must NOT crash the server —
        # it degrades to extractive answers with a note.
        self._synthesizer = self._safe("synthesizer", make_synthesizer, config.synthesize)
        self._judge = self._safe("judge", make_judge, config.judge) or make_judge("lexical")
        self._decomposer = self._safe("decomposer", make_decomposer, config.decompose)
        self._refiner = self._safe("refiner", make_refiner, config.refine)
        # The judge that VERIFIES synthesised prose (semantic entailment, incl.
        # cross-lingual). This is what stops genuine AI synthesis from being
        # wrongly rejected by lexical word-overlap. Prefer an explicit claude
        # JUDGE; otherwise, when Claude synthesis is on, auto-build a FAST Haiku
        # verifier (cheaper/quicker than re-using the synthesis model).
        self._cross_lingual_judge = None
        if config.judge.startswith("claude"):
            self._cross_lingual_judge = self._judge  # explicit claude judge doubles as verifier
        elif config.synthesize.startswith("claude"):
            self._cross_lingual_judge = self._safe(
                "verifier", make_judge, "claude:claude-haiku-4-5-20251001")
        self._engines: dict[str, Engine] = {}
        self._errors: dict[str, str] = {}
        self._facets: Optional[dict] = None
        self._verse_index: Optional[dict] = None
        self._narrators: Optional[NarratorIndex] = None

    def _safe(self, label: str, factory, spec):
        """Build an optional (often LLM-backed) provider without crashing on error."""
        try:
            return factory(spec)
        except Exception as exc:  # noqa: BLE001 - a bad key/spec must not down the server
            if spec and spec != "none":
                self.provider_notes.append(f"{label} '{spec}' unavailable: {exc}")
            return None

    @property
    def n_documents(self) -> int:
        return len(self.docs)

    def verse_index(self) -> dict:
        """``(surah, ayah) -> verse Document`` for cross-referencing, built once."""
        if self._verse_index is None:
            self._verse_index = build_verse_index(self.docs)
        return self._verse_index

    def narrators(self) -> NarratorIndex:
        """The rijāl / narrator index (chain reading + grade attributions), built once."""
        if self._narrators is None:
            self._narrators = NarratorIndex(self.docs)
        return self._narrators

    def crossref(self, engine: "Engine") -> CrossReferencer:
        """A CrossReferencer bound to a built engine's retriever."""
        return CrossReferencer(engine.answers.retriever, self.verse_index())

    def facets(self) -> dict:
        """What's actually in this corpus: source books and evidence types.

        Powers the UI filter panel. Computed once from the loaded documents
        (joined with registry titles/confidence) and cached.
        """
        if self._facets is not None:
            return self._facets
        from collections import Counter

        src_count: Counter = Counter()
        type_count: Counter = Counter()
        src_types: dict[str, set[str]] = {}
        for d in self.docs:
            sid = d.citation.source_id
            src_count[sid] += 1
            type_count[d.evidence_type.value] += 1
            src_types.setdefault(sid, set()).add(d.evidence_type.value)

        sources = []
        for sid, n in src_count.most_common():
            meta = self.sources_meta.get(sid)
            sources.append({
                "id": sid,
                "title": meta.title if meta else sid,
                "confidence": meta.confidence.value if meta else None,
                "count": n,
                "evidence_types": sorted(src_types.get(sid, ())),
            })
        self._facets = {
            "sources": sources,
            "evidence_types": [{"type": t, "count": n} for t, n in type_count.most_common()],
        }
        return self._facets

    @property
    def embedders(self) -> list[str]:
        return list(self.config.embedders)

    @property
    def default_embedder(self) -> str:
        return self.config.default_embedder

    def embedder_state(self, spec: str) -> str:
        """``ready`` (built), ``failed`` (build errored), or ``lazy`` (not yet built)."""
        if spec in self._engines:
            return "ready"
        if spec in self._errors:
            return "failed"
        return "lazy"

    def error_for(self, spec: str) -> Optional[str]:
        return self._errors.get(spec)

    def engine(self, spec: Optional[str] = None) -> Engine:
        """Return the Engine for ``spec`` (default embedder if None), building it once."""
        spec = spec or self.default_embedder
        if spec not in self.config.embedders:
            raise EmbedderUnavailable(
                f"Embedder {spec!r} is not enabled. Available: "
                + ", ".join(self.config.embedders)
            )
        if spec in self._engines:
            return self._engines[spec]
        if spec in self._errors:
            raise EmbedderUnavailable(self._errors[spec])
        try:
            retriever = self._build_retriever(spec)
        except Exception as exc:  # noqa: BLE001 - report, don't crash the server
            self._errors[spec] = str(exc)
            raise EmbedderUnavailable(str(exc)) from exc
        # A semantic (sentence-transformers) index can bridge scripts; a lexical
        # one cannot. This gates the honest cross-lingual caveat on answers.
        multilingual = spec.startswith(("st:", "sentence-transformers:"))
        engine = Engine(
            answers=AnswerGenerator(
                retriever,
                synthesizer=self._synthesizer,
                known_source_ids=self.known,
                judge=self._judge,
                decomposer=self._decomposer,
                multilingual=multilingual,
                refiner=self._refiner,
                cross_lingual_judge=self._cross_lingual_judge,
            ),
            lectures=LectureGenerator(
                retriever, synthesizer=self._synthesizer, judge=self._judge
            ),
        )
        self._engines[spec] = engine
        return engine

    def _build_retriever(self, spec: str) -> Retriever:
        """Build (or load from the on-disk cache) the retriever for one embedder.

        With ``cache_dir`` set, vectors are cached per embedder — so a semantic
        index embedded once at build time loads instantly at runtime instead of
        re-embedding the whole corpus on every start.
        """
        embedder = make_embedder(spec)
        if self.config.cache_dir is None:
            return build_index(self.docs, embedder=embedder)
        safe = spec.replace("/", "_").replace(":", "_")
        cache_path = Path(self.config.cache_dir) / f"{safe}.pkl"
        store = build_persistent_index(self.docs, embedder, cache_path)
        return Retriever(store)


def build_stack(config: Optional[AppConfig] = None) -> Stack:
    """Load the corpus and prepare the generators (default index built eagerly).

    Pure pipeline code — no web dependency — so it is unit-testable on its own
    and reused by both the API and any embedded use.
    """
    config = config or AppConfig()
    docs = list(iter_knowledge_dir(config.knowledge_dir))
    if not docs:
        raise RuntimeError(
            f"No documents found under {config.knowledge_dir}. Build the corpus "
            "first (python scripts/ingest.py) or point --knowledge-dir at a "
            "directory of .jsonl knowledge files."
        )
    known = _load_known_ids(config.registry_path)
    sources_meta = _load_sources_meta(config.registry_path)
    stack = Stack(docs, config, known, sources_meta)
    stack.engine(config.default_embedder)  # eager: validate corpus + default index
    return stack


def _load_known_ids(registry_path: Path) -> Optional[set[str]]:
    try:
        return load_registry_ids(registry_path)
    except FileNotFoundError:
        return None


def _load_sources_meta(registry_path: Path) -> dict[str, Source]:
    try:
        return {s.id: s for s in load_sources(registry_path)}
    except FileNotFoundError:
        return {}


# ---------------------------------------------------------------------------
# JSON payload builders (structured, so the browser can render badges itself)
# ---------------------------------------------------------------------------


def answer_to_payload(answer: Answer, markdown: str) -> dict:
    return {"answer": answer.to_dict(), "markdown": markdown}


def lecture_to_payload(lecture: Lecture) -> dict:
    return {
        "topic": lecture.topic,
        "generated_on": lecture.generated_on,
        "sections": [
            {
                "title": s.title,
                "body": s.body,
                "synthesized": s.synthesized,
                "note": s.note or "",
                "evidence": [
                    {
                        "text": r.document.text.strip(),
                        "reference": r.document.citation.reference_string(),
                        "confidence": r.document.confidence.value,
                        "evidence_type": r.document.evidence_type.value,
                        "translation": r.document.citation.translation,
                        "view_status": r.document.view_status.value if r.document.view_status else None,
                        "citation": r.document.citation.to_dict(),
                    }
                    for r in s.evidence
                ],
            }
            for s in lecture.sections
        ],
        "markdown": lecture.to_markdown(),
    }


def _related_item(item) -> dict:
    """One cross-reference row, shaped like a lecture evidence item for the drawer."""
    doc = item.document
    return {
        "text": doc.text.strip(),
        "reference": doc.citation.reference_string(),
        "confidence": doc.confidence.value,
        "evidence_type": doc.evidence_type.value,
        "translation": doc.citation.translation,
        "view_status": doc.view_status.value if doc.view_status else None,
        "citation": doc.citation.to_dict(),
        "link_type": item.link_type,
        "similarity": round(item.similarity, 4),
    }


def crossref_to_payload(result: CrossRefResult) -> dict:
    v = result.verse
    return {
        "verse": {
            "surah": v.citation.surah,
            "ayah": v.citation.ayah,
            "reference": v.citation.reference_string(),
            "text": v.text.strip(),
            "arabic": v.citation.arabic_text,
            "translation": v.citation.translation,
            "confidence": v.confidence.value,
        },
        "tafsir": [_related_item(i) for i in result.tafsir],
        "hadith": [_related_item(i) for i in result.hadith],
        "verses": [_related_item(i) for i in result.verses],
    }


# ---------------------------------------------------------------------------
# FastAPI app
# ---------------------------------------------------------------------------


def create_app(config: Optional[AppConfig] = None, *, stack: Optional[Stack] = None):
    """Build the FastAPI application.

    ``stack`` lets tests inject a pre-built (small-corpus) stack; otherwise it is
    built from ``config`` at creation time. Raises a clear ImportError with an
    install hint if FastAPI isn't available.
    """
    try:
        from fastapi import FastAPI
        from fastapi.responses import HTMLResponse, JSONResponse
    except ImportError as exc:  # pragma: no cover - exercised only without the extra
        raise ImportError(_FASTAPI_HINT) from exc

    stack = stack or build_stack(config)

    # Optionally expose a remote MCP endpoint at /mcp from this same process, so
    # one Space serves the web UI *and* lets Claude connect by URL — sharing the
    # single loaded corpus. Gated on ENABLE_MCP; the mcp extra must be installed.
    mcp_ctx = _maybe_build_mcp(stack)
    app_kwargs: dict = {}
    if mcp_ctx is not None:
        from contextlib import asynccontextmanager

        _mcp, _mcp_app, _lifespan_cm = mcp_ctx

        @asynccontextmanager
        async def lifespan(_app):
            async with _lifespan_cm:
                yield

        app_kwargs["lifespan"] = lifespan

    app = FastAPI(
        title="Shia-Aalim",
        description="Evidence-first Twelver Shia research & lecture assistant. "
        "No citation = not a fact.",
        version="0.1.0",
        **app_kwargs,
    )
    app.state.stack = stack

    @app.get("/", response_class=HTMLResponse)
    async def index() -> str:
        return INDEX_HTML

    @app.get("/api/status")
    async def status() -> dict:
        cfg = stack.config
        return {
            "documents": stack.n_documents,
            "embedders": [
                {"spec": spec, "state": stack.embedder_state(spec),
                 "default": spec == stack.default_embedder}
                for spec in stack.embedders
            ],
            "default_embedder": stack.default_embedder,
            "synthesizer": cfg.synthesize,
            "judge": cfg.judge,
            "decomposer": cfg.decompose,
            "refiner": cfg.refine,
            # Which AI features are actually live (built OK with a working key).
            "ai": {
                "synthesis": stack._synthesizer is not None,
                "refine": stack._refiner is not None,
                "translate": stack._cross_lingual_judge is not None,
            },
            "provider_notes": stack.provider_notes,
            "default_k": cfg.default_k,
        }

    @app.get("/api/sources")
    async def sources() -> dict:
        return stack.facets()

    @app.post("/api/answer")
    async def api_answer(body: AskBody):
        question = (body.question or "").strip()
        if not question:
            return JSONResponse({"error": "question is required"}, status_code=400)
        try:
            engine = stack.engine(body.embedder)
        except EmbedderUnavailable as exc:
            return JSONResponse({"error": _embedder_error(body.embedder, exc)}, status_code=503)
        k = _clamp_int(body.k, default=stack.config.default_k, lo=1, hi=25)
        lang = (body.answer_language or "en").lower()
        if lang not in ("en", "ur", "ar"):
            lang = "en"
        answer = engine.answers.answer(
            question,
            k=k,
            evidence_types=_parse_types(body.evidence_types),
            source_ids=_parse_sources(body.source_ids),
            min_confidence=_parse_confidence(body.min_confidence),
            answer_language=lang,
        )
        markdown = engine.answers.format_markdown(answer)
        payload = answer_to_payload(answer, markdown)
        payload["embedder"] = body.embedder or stack.default_embedder
        return payload

    @app.post("/api/lecture")
    async def api_lecture(body: LectureBody):
        topic = (body.topic or "").strip()
        if not topic:
            return JSONResponse({"error": "topic is required"}, status_code=400)
        try:
            engine = stack.engine(body.embedder)
        except EmbedderUnavailable as exc:
            return JSONResponse({"error": _embedder_error(body.embedder, exc)}, status_code=503)
        depth = _clamp_int(body.depth, default=4, lo=1, hi=10)
        lecture = engine.lectures.generate(
            topic, depth=depth, source_ids=_parse_sources(body.source_ids)
        )
        payload = lecture_to_payload(lecture)
        payload["embedder"] = body.embedder or stack.default_embedder
        return payload

    @app.post("/api/compare")
    async def api_compare(body: CompareBody):
        question = (body.question or "").strip()
        if not question:
            return JSONResponse({"error": "question is required"}, status_code=400)
        sources = [s for s in (body.sources or []) if s]
        if not sources:
            return JSONResponse({"error": "select at least one book to compare"}, status_code=400)
        try:
            engine = stack.engine(body.embedder)
        except EmbedderUnavailable as exc:
            return JSONResponse({"error": _embedder_error(body.embedder, exc)}, status_code=503)

        truncated = len(sources) > MAX_COMPARE_SOURCES
        sources = sources[:MAX_COMPARE_SOURCES]
        k = _clamp_int(body.k, default=4, lo=1, hi=15)
        types = _parse_types(body.evidence_types)
        conf = _parse_confidence(body.min_confidence)
        titles = {s["id"]: s["title"] for s in stack.facets()["sources"]}

        columns = []
        for sid in sources:
            # Same question, each book answered on its own evidence only.
            ans = engine.answers.answer(
                question, k=k, evidence_types=types, source_ids={sid}, min_confidence=conf
            )
            columns.append({
                "source_id": sid,
                "title": titles.get(sid, sid),
                "answer": ans.to_dict(),
                "markdown": engine.answers.format_markdown(ans),
            })
        return {
            "question": question,
            "embedder": body.embedder or stack.default_embedder,
            "columns": columns,
            "truncated": truncated,
        }

    @app.post("/api/crossref")
    async def api_crossref(body: CrossrefBody):
        if body.surah is None or body.ayah is None:
            return JSONResponse({"error": "surah and ayah are required"}, status_code=400)
        try:
            engine = stack.engine(body.embedder)
        except EmbedderUnavailable as exc:
            return JSONResponse({"error": _embedder_error(body.embedder, exc)}, status_code=503)
        k = _clamp_int(body.k, default=5, lo=1, hi=15)
        result = stack.crossref(engine).related(int(body.surah), int(body.ayah), k=k)
        if result is None:
            return JSONResponse(
                {"error": f"Verse {body.surah}:{body.ayah} is not in the loaded corpus."},
                status_code=404,
            )
        payload = crossref_to_payload(result)
        payload["embedder"] = body.embedder or stack.default_embedder
        return payload

    @app.get("/api/rijal/summary")
    async def rijal_summary() -> dict:
        idx = stack.narrators()
        s = idx.grade_summary()
        s["top_narrators"] = idx.top_narrators(20)
        s["narrator_count"] = idx.narrator_count
        return s

    @app.post("/api/rijal/narrator")
    async def rijal_narrator(body: NarratorBody):
        name = (body.name or "").strip()
        if not name:
            return JSONResponse({"error": "a narrator name is required"}, status_code=400)
        idx = stack.narrators()
        prof = idx.lookup(name)
        limit = _clamp_int(body.limit, default=25, lo=1, hi=100)
        # De-duplicate narrations (a narrator can appear once per hadith) and shape them.
        seen: set[str] = set()
        narrations = []
        for men in prof.mentions:
            if men.doc_id in seen:
                continue
            seen.add(men.doc_id)
            doc = idx.document(men.doc_id)
            if doc is not None:
                narrations.append(_narration_payload(doc, position=men.position,
                                                      chain_length=men.chain_length))
            if len(narrations) >= limit:
                break
        return {
            "query": prof.query,
            "matched_names": prof.matched_names,
            "narration_count": prof.narration_count,
            "grade_distribution": prof.grade_distribution,
            "narrations": narrations,
        }

    if mcp_ctx is not None:
        # Mounted at "/" so the endpoint lands at the MCP path (default /mcp),
        # sharing this app's already-loaded corpus.
        app.mount("/", _mcp_app)

    return app


def _maybe_build_mcp(stack: "Stack"):
    """Build the mountable MCP app when ENABLE_MCP is set, else return None.

    Returns ``(mcp, asgi_app, lifespan_cm)`` or ``None``. Failures (missing
    extra, etc.) are logged and treated as "MCP off" — they never break the web
    app.
    """
    if os.environ.get("ENABLE_MCP", "").strip().lower() not in ("1", "true", "yes", "on"):
        return None
    try:
        from . import mcp_server
        token = os.environ.get("MCP_BEARER_TOKEN") or None
        mcp, mcp_app = mcp_server.build_http_app(stack=stack, bearer_token=token)
        path = mcp.settings.streamable_http_path
        notes = []
        if token:
            notes.append("bearer-token protected")
        if mcp.settings.auth:
            notes.append(f"OAuth enabled, client_id={os.environ.get('MCP_OAUTH_CLIENT_ID', 'shia-aalim-mcp')}")
        suffix = f" ({', '.join(notes)})" if notes else ""
        print(f"[shia-aalim] remote MCP endpoint enabled at {path}{suffix}", file=sys.stderr)
        return mcp, mcp_app, mcp_server.session_lifespan(mcp)
    except Exception as exc:  # pragma: no cover - defensive
        print(f"[shia-aalim] ENABLE_MCP set but MCP could not start: {exc}", file=sys.stderr)
        return None


def _narration_payload(doc: Document, *, position: int = -1, chain_length: int = 0) -> dict:
    """A hadith shaped for the rijāl view + drawer: evidence fields + chain + gradings."""
    reading = extract_chain(doc.text)
    return {
        "text": doc.text.strip(),
        "reference": doc.citation.reference_string(),
        "confidence": doc.confidence.value,
        "evidence_type": doc.evidence_type.value,
        "translation": doc.citation.translation,
        "view_status": doc.view_status.value if doc.view_status else None,
        "citation": doc.citation.to_dict(),
        "grade": doc.citation.grade.value,
        "chain": reading.narrators,
        "position": position,
        "chain_length": chain_length or len(reading.narrators),
        "attributions": [
            {"attributor": a.attributor, "grade": a.grade, "work": a.work}
            for a in parse_grade_source(doc.citation.grade_source)
        ],
    }


def _parse_types(values: Optional[list[str]]) -> Optional[list[EvidenceType]]:
    """Turn incoming strings into EvidenceType values; unknown ones are dropped."""
    if not values:
        return None
    out: list[EvidenceType] = []
    for v in values:
        try:
            out.append(EvidenceType(v))
        except ValueError:
            continue
    return out or None


def _parse_sources(values: Optional[list[str]]) -> Optional[set[str]]:
    if not values:
        return None
    picked = {v for v in values if v}
    return picked or None


def _parse_confidence(value: Optional[str]) -> ConfidenceLevel:
    """Map a floor string to a ConfidenceLevel; default LOW (the generator default)."""
    if not value:
        return ConfidenceLevel.LOW
    try:
        return ConfidenceLevel(value)
    except ValueError:
        return ConfidenceLevel.LOW


def _embedder_error(spec: Optional[str], exc: Exception) -> str:
    return (
        f"The '{spec}' embedder is not available in this environment: {exc}. "
        "Semantic models (st:…) need the [embeddings] extra and a reachable "
        "model; switch back to the tfidf index."
    )


def _clamp_int(value, *, default: int, lo: int, hi: int) -> int:
    try:
        n = int(value)
    except (TypeError, ValueError):
        return default
    return max(lo, min(hi, n))


# ---------------------------------------------------------------------------
# Single-page UI — self-contained (no external assets), so it works offline.
# ---------------------------------------------------------------------------

INDEX_HTML = r"""<!doctype html>
<html lang="en">
<head>
<meta charset="utf-8">
<meta name="viewport" content="width=device-width, initial-scale=1">
<title>Shia-Aalim — evidence-first research assistant</title>
<style>
  :root {
    --bg: #0c0f13; --panel: #141922; --panel2: #1b212c; --line: #29313d;
    --ink: #e9eef4; --muted: #93a1b2; --accent: #17a67c; --accent2: #128a67;
    --accent-soft: rgba(23,166,124,.14); --gold: #d8ad5f; --gold-soft: rgba(216,173,95,.14);
    --high: #2ea043; --medium: #d29922; --low: #db6d28; --unverified: #6e7681;
    --quran: #7c5cff; --hadith: #17a67c; --tafsir: #c46fd6;
    --historical: #d2792a; --scholarly: #4b8ef0;
    --shadow: 0 1px 2px rgba(0,0,0,.24), 0 6px 20px rgba(0,0,0,.22);
    --shadow-sm: 0 1px 2px rgba(0,0,0,.2);
    --r: 12px; --r-sm: 9px;
    --font-sans: -apple-system, BlinkMacSystemFont, "Segoe UI", Roboto, Helvetica, Arial, sans-serif;
    --font-serif: "Iowan Old Style", "Palatino Linotype", Palatino, Georgia, serif;
    --font-arabic: "Noto Naskh Arabic", "Amiri", "Scheherazade New", "Traditional Arabic", serif;
    --font-urdu: "Noto Nastaliq Urdu", "Jameel Noori Nastaleeq", "Noto Naskh Arabic", serif;
  }
  @media (prefers-color-scheme: light) {
    :root {
      --bg: #f6f7f5; --panel: #ffffff; --panel2: #eef1ee; --line: #e0e4e0;
      --ink: #14181d; --muted: #5a6672; --accent: #0f8f6a; --accent2: #0b7455;
      --accent-soft: rgba(15,143,106,.10); --gold: #b8863a; --gold-soft: rgba(184,134,58,.12);
      --shadow: 0 1px 2px rgba(20,30,40,.06), 0 8px 24px rgba(20,30,40,.07);
      --shadow-sm: 0 1px 2px rgba(20,30,40,.06);
    }
  }
  * { box-sizing: border-box; }
  html { scroll-behavior: smooth; }
  body {
    margin: 0; background: var(--bg); color: var(--ink);
    font: 15px/1.6 var(--font-sans); -webkit-font-smoothing: antialiased; text-rendering: optimizeLegibility;
  }
  header {
    padding: 16px 22px; border-bottom: 1px solid var(--line);
    background: color-mix(in srgb, var(--panel) 88%, transparent);
    backdrop-filter: saturate(1.4) blur(8px); position: sticky; top: 0; z-index: 15;
  }
  .hwrap { display: flex; align-items: center; gap: 14px; max-width: 1060px; margin: 0 auto; }
  .brand { display: flex; align-items: center; gap: 13px; flex: 1; min-width: 0; }
  .uilang { display: inline-flex; gap: 3px; padding: 3px; background: var(--panel2); border: 1px solid var(--line); border-radius: 999px; flex: none; }
  .ui-pill { padding: 5px 12px; border: 0; background: transparent; color: var(--muted); border-radius: 999px; cursor: pointer; font-size: 12.5px; font-weight: 600; }
  .ui-pill.active { background: var(--panel); color: var(--accent); box-shadow: var(--shadow-sm); }
  .ui-pill .native { font-family: var(--font-urdu); font-size: 15px; }
  /* Urdu interface: right-to-left, Urdu typeface for the chrome. */
  html[dir=rtl] body { font-family: var(--font-urdu); }
  html[dir=rtl] .qtitle, html[dir=rtl] h1 { font-family: var(--font-urdu); }
  html[dir=rtl] .ref, html[dir=rtl] code, html[dir=rtl] input, html[dir=rtl] .cnt,
  html[dir=rtl] .htime, html[dir=rtl] select { direction: ltr; }
  html[dir=rtl] .badges, html[dir=rtl] .frow, html[dir=rtl] .row { direction: rtl; }
  html[dir=rtl] .ev .txt:not(.ar) { text-align: right; }
  html[dir=rtl] input[type=text] { text-align: right; }
  .brand .mark {
    width: 40px; height: 40px; border-radius: 11px; flex: none; display: grid; place-items: center;
    font-size: 21px; color: #fff; background: linear-gradient(150deg, var(--accent), var(--accent2));
    box-shadow: 0 4px 14px var(--accent-soft); border: 1px solid color-mix(in srgb, var(--accent) 60%, #000);
  }
  header h1 { margin: 0; font-family: var(--font-serif); font-size: 21px; font-weight: 650; letter-spacing: .2px; }
  header h1 .ar { font-family: var(--font-arabic); font-size: 18px; color: var(--gold); margin-left: 6px; font-weight: 500; }
  header .tag { color: var(--muted); font-size: 12.5px; margin-top: 1px; }
  header .tag b { color: var(--accent); font-weight: 600; }
  main { max-width: 1060px; margin: 0 auto; padding: 26px 20px 90px; }
  .tabs {
    display: inline-flex; gap: 2px; margin-bottom: 22px; padding: 4px;
    background: var(--panel2); border: 1px solid var(--line); border-radius: 999px; flex-wrap: wrap;
  }
  .tab {
    padding: 8px 17px; border: 0; border-radius: 999px; background: transparent;
    color: var(--muted); cursor: pointer; font-size: 13.5px; font-weight: 550; transition: all .15s;
  }
  .tab:hover { color: var(--ink); }
  .tab.active { background: var(--panel); color: var(--accent); box-shadow: var(--shadow-sm); }
  .row { display: flex; gap: 10px; flex-wrap: wrap; align-items: stretch; }
  input[type=text] {
    flex: 1 1 320px; padding: 13px 15px; border-radius: var(--r); font-size: 15px;
    border: 1px solid var(--line); background: var(--panel); color: var(--ink); transition: border-color .15s, box-shadow .15s;
  }
  input[type=text]:focus, input[type=number]:focus, select:focus {
    outline: none; border-color: var(--accent); box-shadow: 0 0 0 3px var(--accent-soft);
  }
  input[type=number] {
    width: 84px; padding: 13px 10px; border-radius: var(--r); font-size: 15px;
    border: 1px solid var(--line); background: var(--panel); color: var(--ink);
  }
  button.go {
    padding: 13px 22px; border: 0; border-radius: var(--r); cursor: pointer;
    background: linear-gradient(150deg, var(--accent), var(--accent2)); color: #fff;
    font-size: 15px; font-weight: 600; box-shadow: 0 2px 10px var(--accent-soft); transition: filter .15s, transform .05s;
  }
  button.go:hover { filter: brightness(1.06); }
  button.go:active { transform: translateY(1px); }
  button.go:disabled { opacity: .5; cursor: default; filter: none; }
  label.fld { display: flex; flex-direction: column; gap: 4px; font-size: 11px; color: var(--muted); text-transform: uppercase; letter-spacing: .4px; }
  .langsel { display: flex; align-items: center; gap: 8px; margin: 12px 2px 0; flex-wrap: wrap; }
  .langsel .lbl { font-size: 12px; color: var(--muted); text-transform: uppercase; letter-spacing: .5px; }
  .lang-pills { display: inline-flex; gap: 3px; padding: 3px; background: var(--panel2); border: 1px solid var(--line); border-radius: 999px; }
  .lang-pill { padding: 6px 14px; border: 0; background: transparent; color: var(--muted); border-radius: 999px; cursor: pointer; font-size: 13px; font-weight: 550; }
  .lang-pill.active { background: var(--panel); color: var(--accent); box-shadow: var(--shadow-sm); }
  .lang-pill .native { font-family: var(--font-urdu); font-size: 15px; }
  .hint { color: var(--muted); font-size: 13px; margin: 10px 2px 0; }
  .status { color: var(--muted); font-size: 12.5px; margin-top: 14px; }
  .result { margin-top: 22px; }
  .qtitle { font-family: var(--font-serif); font-size: 20px; font-weight: 650; margin: 0 0 6px; line-height: 1.35; }
  .subq { color: var(--muted); font-size: 13px; margin: 0 0 14px; }
  .summary {
    background: linear-gradient(180deg, var(--accent-soft), transparent), var(--panel);
    border: 1px solid var(--line); border-left: 3px solid var(--accent);
    padding: 16px 18px; border-radius: var(--r); margin: 0 0 20px; white-space: pre-wrap;
    box-shadow: var(--shadow-sm); font-size: 15.5px; line-height: 1.7;
  }
  .summary .lbl { color: var(--accent); font-size: 11px; font-weight: 700; text-transform: uppercase; letter-spacing: .5px; margin-bottom: 8px; white-space: normal; }
  .summary.rtl { direction: rtl; text-align: right; font-family: var(--font-urdu); font-size: 19px; line-height: 2.15; border-left: 0; border-right: 3px solid var(--gold); }
  .summary.rtl .lbl { color: var(--gold); direction: rtl; font-family: var(--font-sans); }
  .evhead { font-size: 13px; text-transform: uppercase; letter-spacing: .6px; color: var(--muted); margin: 18px 0 8px; }
  .ev {
    background: var(--panel); border: 1px solid var(--line); border-radius: var(--r);
    padding: 13px 15px; margin-bottom: 11px; box-shadow: var(--shadow-sm);
  }
  .ev .txt { margin: 0 0 8px; }
  .ev .ar { direction: rtl; text-align: right; font-family: var(--font-arabic); font-size: 19px; line-height: 2.05; }
  .ev .ur-inline { direction: rtl; text-align: right; font-family: var(--font-urdu); font-size: 16px; line-height: 2.1; color: var(--ink); margin: 4px 0 8px; }
  .badges { display: flex; gap: 6px; flex-wrap: wrap; align-items: center; }
  .badge {
    font-size: 11px; font-weight: 700; text-transform: uppercase; letter-spacing: .4px;
    padding: 2px 8px; border-radius: 999px; color: #fff;
  }
  .ref { color: var(--muted); font-size: 12.5px; margin-left: auto; font-variant-numeric: tabular-nums; }
  .b-high { background: var(--high); } .b-medium { background: var(--medium); }
  .b-low { background: var(--low); } .b-unverified { background: var(--unverified); }
  .t-quran { background: var(--quran); } .t-hadith { background: var(--hadith); }
  .t-tafsir { background: var(--tafsir); } .t-historical { background: var(--historical); }
  .t-scholarly_opinion { background: var(--scholarly); } .t-biographical { background: #8a7a5c; }
  .t-linguistic { background: #5c8a7a; } .t-historical { background: var(--historical); }
  .caveats { margin-top: 20px; border-top: 1px dashed var(--line); padding-top: 14px; }
  .caveats .lbl { color: var(--low); font-size: 12px; text-transform: uppercase; letter-spacing: .5px; }
  .caveats ul { margin: 8px 0 0; padding-left: 18px; }
  .caveats li { color: var(--muted); font-size: 13px; margin-bottom: 5px; }
  .sec { margin-bottom: 22px; }
  .sec h3 { margin: 0 0 4px; font-size: 16px; }
  .sec .note { color: var(--muted); font-size: 13px; font-style: italic; margin: 2px 0 8px; }
  .sec .body { white-space: pre-wrap; margin: 6px 0 10px; }
  .synth { color: var(--high); font-size: 12px; font-weight: 600; }
  .empty { color: var(--muted); padding: 20px 0; }
  .cols { display: flex; gap: 14px; overflow-x: auto; padding-bottom: 10px; }
  .col { flex: 0 0 320px; max-width: 360px; border: 1px solid var(--line); border-radius: 10px; padding: 12px 12px 4px; background: var(--panel2); }
  .col h4 { margin: 0 0 2px; font-size: 14.5px; }
  .col .meta { color: var(--muted); font-size: 12px; margin-bottom: 10px; }
  .col .ev { background: var(--panel); }
  .col .empty { padding: 6px 0 12px; font-size: 13px; }
  .hitem { display: flex; align-items: center; gap: 12px; border: 1px solid var(--line); border-radius: 10px; padding: 10px 12px; margin-bottom: 8px; background: var(--panel); }
  .hmeta { display: flex; align-items: center; gap: 10px; flex: 1; min-width: 0; }
  .htype { font-size: 11px; font-weight: 700; text-transform: uppercase; letter-spacing: .4px; padding: 2px 8px; border-radius: 999px; color: #fff; flex: none; }
  .ht-ask { background: var(--accent); } .ht-lecture { background: var(--quran); } .ht-compare { background: var(--hadith); }
  .hlabel { flex: 1; overflow: hidden; text-overflow: ellipsis; white-space: nowrap; }
  .htime { color: var(--muted); font-size: 12px; flex: none; font-variant-numeric: tabular-nums; }
  .hact { display: flex; gap: 6px; flex: none; }
  .spinner { color: var(--muted); padding: 20px 0; }
  .spinner.building { color: var(--medium); }
  .spinner.building code { color: var(--ink); }
  .spinner::after { content: ""; animation: dots 1.2s steps(4,end) infinite; }
  @keyframes dots { 0%{content:""} 25%{content:"·"} 50%{content:"··"} 75%{content:"···"} }
  footer { color: var(--muted); font-size: 12px; text-align: center; padding: 30px 0 10px; }
  code { background: var(--panel2); padding: 1px 5px; border-radius: 4px; font-size: 12.5px; }
  select {
    padding: 11px 12px; border-radius: 10px; border: 1px solid var(--line);
    background: var(--panel); color: var(--ink); font-size: 14px;
  }
  select:disabled { opacity: .6; }
  .toolbar { display: flex; gap: 8px; margin: 4px 0 14px; }
  .toolbar.hidden { display: none; }
  button.mini {
    padding: 6px 12px; border: 1px solid var(--line); border-radius: 8px; cursor: pointer;
    background: var(--panel); color: var(--ink); font-size: 12.5px;
  }
  button.mini:hover { border-color: var(--accent); color: var(--accent); }
  .idxrow { display: flex; align-items: center; gap: 8px; margin-bottom: 14px; color: var(--muted); font-size: 13px; }
  .idxnote { font-size: 12px; color: var(--muted); }
  details.filters {
    border: 1px solid var(--line); border-radius: 10px; background: var(--panel);
    padding: 0 14px; margin: 10px 0 4px;
  }
  details.filters summary {
    cursor: pointer; padding: 11px 0; font-size: 13.5px; color: var(--muted); user-select: none;
  }
  details.filters[open] summary { border-bottom: 1px solid var(--line); margin-bottom: 12px; }
  .filters .active-count { color: var(--accent); font-weight: 600; }
  .fgrid { display: flex; gap: 22px; flex-wrap: wrap; margin-bottom: 12px; }
  .fcol { min-width: 180px; }
  .flabel { font-size: 12px; text-transform: uppercase; letter-spacing: .5px; color: var(--muted); margin: 6px 0 8px; }
  .checks { display: flex; flex-direction: column; gap: 6px; }
  .srclist { max-height: 220px; overflow-y: auto; padding: 4px 6px 4px 2px; border: 1px solid var(--line); border-radius: 8px; }
  label.chk { display: flex; align-items: center; gap: 8px; font-size: 13.5px; cursor: pointer; padding: 1px 0; }
  label.chk input { accent-color: var(--accent); }
  label.chk .cnt { color: var(--muted); font-size: 12px; margin-left: auto; font-variant-numeric: tabular-nums; }
  label.chk .cdot { width: 8px; height: 8px; border-radius: 50%; display: inline-block; flex: none; }
  .srcsearch { width: 100%; padding: 8px 10px; margin-bottom: 8px; border-radius: 8px; border: 1px solid var(--line); background: var(--panel2); color: var(--ink); font-size: 13px; }
  .frow { display: flex; gap: 8px; margin-top: 8px; align-items: center; }
  .fmini { padding: 4px 10px; border: 1px solid var(--line); border-radius: 7px; background: var(--panel); color: var(--muted); cursor: pointer; font-size: 12px; }
  .fmini:hover { border-color: var(--accent); color: var(--accent); }
  .cdot-high { background: var(--high); } .cdot-medium { background: var(--medium); }
  .cdot-low { background: var(--low); } .cdot-unverified { background: var(--unverified); }
  .ev.clickable { cursor: pointer; transition: border-color .12s; }
  .ev.clickable:hover { border-color: var(--accent); }
  .ev .more { color: var(--accent); font-size: 12px; margin-left: 8px; white-space: nowrap; }
  #drawerOverlay {
    position: fixed; inset: 0; background: rgba(0,0,0,.45); opacity: 0; pointer-events: none;
    transition: opacity .18s; z-index: 20;
  }
  #drawerOverlay.open { opacity: 1; pointer-events: auto; }
  #drawer {
    position: fixed; top: 0; right: 0; height: 100%; width: min(460px, 92vw);
    background: var(--panel); border-left: 1px solid var(--line); z-index: 21;
    transform: translateX(100%); transition: transform .2s ease; overflow-y: auto;
    box-shadow: -12px 0 40px rgba(0,0,0,.25);
  }
  #drawer.open { transform: translateX(0); }
  .drawer-head { display: flex; align-items: flex-start; gap: 10px; padding: 18px 18px 12px; border-bottom: 1px solid var(--line); position: sticky; top: 0; background: var(--panel); }
  .drawer-head h2 { margin: 0; font-size: 16px; line-height: 1.35; flex: 1; }
  .drawer-close { border: 0; background: var(--panel2); color: var(--ink); border-radius: 8px; width: 30px; height: 30px; font-size: 18px; cursor: pointer; flex: none; }
  .drawer-body { padding: 16px 18px 40px; }
  .drawer-body .ar { direction: rtl; text-align: right; font-family: var(--font-arabic); font-size: 20px; line-height: 2.05; margin: 4px 0 14px; }
  .drawer-body .en { font-size: 15px; line-height: 1.65; margin: 0 0 14px; }
  .drawer-body .ur { direction: rtl; text-align: right; font-family: var(--font-urdu); font-size: 18px; line-height: 2.2; margin: 2px 0 6px; }
  .drawer-body .grp { margin: 14px 0; }
  .drawer-body .k { font-size: 11px; text-transform: uppercase; letter-spacing: .5px; color: var(--muted); }
  .drawer-body .v { font-size: 14px; margin-top: 2px; }
  .kv { display: grid; grid-template-columns: auto 1fr; gap: 4px 14px; font-size: 13.5px; }
  .kv .k { align-self: center; }
  .drawer-body .src { color: var(--muted); font-size: 13px; }
  .xref-btn { margin: 6px 0 4px; }
  .linktag { font-size: 10px; font-weight: 700; text-transform: uppercase; letter-spacing: .4px; padding: 2px 7px; border-radius: 999px; }
  .lt-explicit { background: var(--high); color: #fff; }
  .lt-thematic { background: var(--panel2); color: var(--muted); border: 1px solid var(--line); }
  .chain { display: flex; flex-wrap: wrap; align-items: center; gap: 4px; margin-top: 6px; }
  .cn { background: var(--panel2); border: 1px solid var(--line); border-radius: 6px; padding: 2px 8px; font-size: 13px; }
  .carrow { color: var(--muted); font-size: 13px; margin: 0 1px; }
  .grade-attr { font-size: 13.5px; margin: 4px 0; }
  .ga-grade { font-weight: 700; }
  .ga-who { color: var(--ink); }
  .grade-dist { display: flex; flex-wrap: wrap; gap: 8px; margin: 8px 0 4px; }
  .gpill { border: 1px solid var(--line); border-radius: 999px; padding: 3px 10px; font-size: 12.5px; }
  .gpill b { font-variant-numeric: tabular-nums; }
  .nchip { border: 1px solid var(--line); border-radius: 999px; padding: 5px 11px; font-size: 13px; cursor: pointer; background: var(--panel); }
  .nchip:hover { border-color: var(--accent); color: var(--accent); }
  .nchip .cnt { color: var(--muted); font-size: 11.5px; margin-left: 5px; }
  .nchips { display: flex; flex-wrap: wrap; gap: 7px; margin-top: 8px; }
  .rcard { border: 1px solid var(--line); border-radius: 10px; padding: 12px 14px; margin-bottom: 12px; background: var(--panel); }
  .rcard h4 { margin: 0 0 6px; font-size: 15px; }
</style>
</head>
<body>
<header>
  <div class="hwrap">
    <div class="brand">
      <div class="mark">☾</div>
      <div>
        <h1>Shia-Aalim <span class="ar">شیعہ عالِم</span></h1>
        <div class="tag" data-i18n="tagline">Evidence-first Twelver (Ithnā ʿAsharī) research &amp; lecture assistant · <b>No citation = not a fact.</b></div>
      </div>
    </div>
    <div class="uilang" title="Interface language">
      <button class="ui-pill active" data-uilang="en" onclick="applyUiLang('en')">EN</button>
      <button class="ui-pill" data-uilang="ur" onclick="applyUiLang('ur')"><span class="native">اردو</span></button>
    </div>
  </div>
</header>
<main>
  <div class="tabs">
    <div class="tab active" data-tab="ask" data-i18n="tab_ask" onclick="switchTab('ask')">Ask a question</div>
    <div class="tab" data-tab="lecture" data-i18n="tab_lecture" onclick="switchTab('lecture')">Prepare a lecture</div>
    <div class="tab" data-tab="compare" data-i18n="tab_compare" onclick="switchTab('compare')">Compare sources</div>
    <div class="tab" data-tab="rijal" data-i18n="tab_rijal" onclick="switchTab('rijal')">Narrators</div>
    <div class="tab" data-tab="history" data-i18n="tab_history" onclick="switchTab('history')">History</div>
  </div>

  <div class="idxrow">
    <label for="embedder" data-i18n="retrieval_index">Retrieval index</label>
    <select id="embedder" disabled onchange="onEmbedderChange()"><option>loading…</option></select>
    <span class="idxnote" id="idxnote"></span>
  </div>

  <section id="pane-ask">
    <div class="row">
      <input type="text" id="q" data-i18n-ph="ask_ph" placeholder="e.g. What does the Qur'an say about justice?" onkeydown="if(event.key==='Enter')ask()">
      <label class="fld"><span data-i18n="evidence">evidence</span><input type="number" id="k" value="6" min="1" max="25"></label>
      <button class="go" id="askBtn" data-i18n="ask_btn" onclick="ask()">Ask</button>
    </div>
    <details class="filters" id="askFilters">
      <summary><span data-i18n="filters">Filters</span> <span class="active-count" id="askFilterCount"></span></summary>
      <div class="fgrid">
        <div class="fcol">
          <div class="flabel">Evidence type</div>
          <div class="checks" id="askTypes"><span class="idxnote">loading…</span></div>
        </div>
        <div class="fcol">
          <div class="flabel">Minimum confidence</div>
          <select id="askConf" onchange="updateFilterCount('ask')">
            <option value="unverified">Any</option>
            <option value="low" selected>Low and up</option>
            <option value="medium">Medium and up</option>
            <option value="high">High only</option>
          </select>
        </div>
      </div>
      <div class="fcol" style="min-width:100%">
        <div class="flabel">Restrict to sources <span class="idxnote">(none checked = search all)</span></div>
        <input type="text" class="srcsearch" placeholder="filter this list…" oninput="filterSrcList('ask', this.value)">
        <div class="checks srclist" id="askSources"></div>
        <div class="frow">
          <button class="fmini" type="button" onclick="setAllSrc('ask', true)" data-i18n="select_all">Select all</button>
          <button class="fmini" type="button" onclick="setAllSrc('ask', false)" data-i18n="clear">Clear</button>
        </div>
      </div>
    </details>
    <div class="langsel" id="langSel" style="display:none">
      <span class="lbl" data-i18n="answer_in">Answer in</span>
      <div class="lang-pills">
        <button class="lang-pill active" data-lang="en" onclick="setAnswerLang('en')">English</button>
        <button class="lang-pill" data-lang="ur" onclick="setAnswerLang('ur')"><span class="native">اردو</span> Urdu</button>
        <button class="lang-pill" data-lang="ar" onclick="setAnswerLang('ar')"><span class="native">العربية</span> Arabic</button>
      </div>
      <span class="idxnote" id="langNote"></span>
    </div>
    <div class="hint" data-i18n="ask_hint">Every answer is grounded in retrieved, cited passages. Weak or disputed evidence is flagged, never hidden.</div>
    <div class="toolbar hidden" id="askTools">
      <button class="mini" data-i18n="copy_md" onclick="copyMd('ask')">⧉ Copy Markdown</button>
      <button class="mini" data-i18n="download_md" onclick="downloadMd('ask')">⭳ Download .md</button>
    </div>
    <div class="result" id="askResult"></div>
  </section>

  <section id="pane-lecture" style="display:none">
    <div class="row">
      <input type="text" id="topic" data-i18n-ph="lecture_ph" placeholder="e.g. The patience (ṣabr) of Imam Husayn (a)" onkeydown="if(event.key==='Enter')lecture()">
      <label class="fld"><span data-i18n="depth">depth</span><input type="number" id="depth" value="4" min="1" max="10"></label>
      <button class="go" id="lecBtn" data-i18n="build_outline" onclick="lecture()">Build outline</button>
    </div>
    <details class="filters" id="lecFilters">
      <summary><span data-i18n="restrict_sources">Restrict to sources</span> <span class="active-count" id="lecFilterCount"></span></summary>
      <input type="text" class="srcsearch" placeholder="filter this list…" oninput="filterSrcList('lec', this.value)">
      <div class="checks srclist" id="lecSources"></div>
      <div class="frow">
        <button class="fmini" type="button" onclick="setAllSrc('lec', true)" data-i18n="select_all">Select all</button>
        <button class="fmini" type="button" onclick="setAllSrc('lec', false)" data-i18n="clear">Clear</button>
      </div>
    </details>
    <div class="hint" data-i18n="lecture_hint">Builds the 11-section majlis/khutbah framework. Evidence sections are filled from cited passages; narrative sections are LLM-written only when a synthesizer is enabled and the prose verifies against the evidence.</div>
    <div class="toolbar hidden" id="lecTools">
      <button class="mini" data-i18n="copy_md" onclick="copyMd('lec')">⧉ Copy Markdown</button>
      <button class="mini" data-i18n="download_md" onclick="downloadMd('lec')">⭳ Download .md</button>
    </div>
    <div class="result" id="lecResult"></div>
  </section>

  <section id="pane-compare" style="display:none">
    <div class="row">
      <input type="text" id="cq" data-i18n-ph="compare_ph" placeholder="e.g. the status of the Ahl al-Bayt (a)" onkeydown="if(event.key==='Enter')compare()">
      <label class="fld"><span data-i18n="per_book">per book</span><input type="number" id="ck" value="4" min="1" max="15"></label>
      <button class="go" id="cmpBtn" data-i18n="compare_btn" onclick="compare()">Compare</button>
    </div>
    <div class="fcol" style="margin:10px 0">
      <div class="flabel">Books to compare <span class="active-count" id="cmpFilterCount"></span> <span class="idxnote">pick 2+ (up to 6)</span></div>
      <input type="text" class="srcsearch" placeholder="filter this list…" oninput="filterSrcList('cmp', this.value)">
      <div class="checks srclist" id="cmpSources"></div>
      <div class="frow">
        <button class="fmini" type="button" onclick="setAllSrc('cmp', true)" data-i18n="select_all">Select all</button>
        <button class="fmini" type="button" onclick="setAllSrc('cmp', false)" data-i18n="clear">Clear</button>
      </div>
    </div>
    <div class="hint" data-i18n="compare_hint">Runs the same question separately against each selected book and lines the answers up side by side — so you can see which books actually speak to it, and how.</div>
    <div class="toolbar hidden" id="cmpTools">
      <button class="mini" data-i18n="copy_md" onclick="copyMd('cmp')">⧉ Copy Markdown</button>
      <button class="mini" data-i18n="download_md" onclick="downloadMd('cmp')">⭳ Download .md</button>
    </div>
    <div class="result" id="cmpResult"></div>
  </section>

  <section id="pane-rijal" style="display:none">
    <div class="row">
      <input type="text" id="rq" data-i18n-ph="rijal_ph" placeholder="look up a narrator, e.g. Yunus Bin Abdul Rahman" onkeydown="if(event.key==='Enter')lookupNarrator()">
      <button class="go" id="rqBtn" data-i18n="lookup_btn" onclick="lookupNarrator()">Look up</button>
    </div>
    <div class="hint" data-i18n="rijal_hint">Reads each narration's chain (isnad) <b>as it appears in the text</b> and surfaces the <b>attributed</b> gradings — a research aid, not a rijāl verdict. The system never grades a narrator or narration itself.</div>
    <div id="rijalSummary" style="margin-top:14px"></div>
    <div class="result" id="rijalResult"></div>
  </section>

  <section id="pane-history" style="display:none">
    <div class="frow" style="justify-content:space-between; align-items:flex-start">
      <div class="hint" style="margin:0" data-i18n="history_hint">Your recent answers, lectures and comparisons — kept in this browser only. Click <b>Open</b> to revisit one instantly (no re-query).</div>
      <button class="fmini" data-i18n="clear_all" onclick="clearHistory()">Clear all</button>
    </div>
    <div id="historyList" style="margin-top:16px"></div>
  </section>

  <div class="status" id="status">Loading corpus status…</div>
</main>
<footer data-i18n="footer">Shia-Aalim · answers are aids to research, not a substitute for a qualified scholar (marjaʿ). Verify every citation against the primary source.</footer>

<div id="drawerOverlay" onclick="closeDrawer()"></div>
<aside id="drawer" aria-hidden="true">
  <div class="drawer-head">
    <h2 id="drawerTitle"></h2>
    <button class="drawer-close" onclick="closeDrawer()" aria-label="Close">×</button>
  </div>
  <div class="drawer-body" id="drawerBody"></div>
</aside>

<script>
function esc(s){ return (s==null?'':String(s)).replace(/[&<>"']/g, c => ({'&':'&amp;','<':'&lt;','>':'&gt;','"':'&quot;',"'":'&#39;'}[c])); }
function isArabic(s){ return /[؀-ۿ]/.test(s||''); }

// ---- Urdu interface (i18n) ------------------------------------------------
var UR = {
  tagline: 'شواہد پر مبنی اثنا عشری شیعہ تحقیق و تقریر کا معاون · <b>بغیر حوالہ کوئی بات حقیقت نہیں۔</b>',
  tab_ask: 'سوال پوچھیں', tab_lecture: 'تقریر تیار کریں', tab_compare: 'مآخذ کا موازنہ',
  tab_rijal: 'راوی / رجال', tab_history: 'سابقہ',
  retrieval_index: 'تلاش کا اشاریہ',
  ask_ph: 'مثلاً: قرآن عدل کے بارے میں کیا کہتا ہے؟',
  evidence: 'شواہد', ask_btn: 'پوچھیں', answer_in: 'جواب کی زبان',
  ask_hint: 'ہر جواب حوالہ شدہ، مستند اقتباسات پر مبنی ہوتا ہے۔ کمزور یا مختلف فیہ شواہد کی نشاندہی کی جاتی ہے، چھپائے نہیں جاتے۔',
  copy_md: '⧉ مارک ڈاؤن کاپی کریں', download_md: '⭳ ڈاؤن لوڈ (.md)',
  lecture_ph: 'مثلاً: امام حسینؑ کا صبر', depth: 'گہرائی', build_outline: 'خاکہ بنائیں',
  lecture_hint: 'گیارہ حصوں پر مشتمل مجلس/خطبہ کا خاکہ بناتا ہے۔ شواہد والے حصے مستند اقتباسات سے بھرے جاتے ہیں؛ بیانیہ حصے صرف تصدیق کے بعد AI لکھتا ہے۔',
  compare_ph: 'مثلاً: اہلِ بیتؑ کا مقام', per_book: 'فی کتاب', compare_btn: 'موازنہ',
  compare_hint: 'ایک ہی سوال کو منتخب کتب پر الگ الگ چلاتا ہے اور جوابات کو ساتھ ساتھ دکھاتا ہے۔',
  rijal_ph: 'کسی راوی کو تلاش کریں، مثلاً: یونس بن عبد الرحمٰن', lookup_btn: 'تلاش کریں',
  rijal_hint: 'ہر روایت کی سند کو <b>جیسا کہ متن میں موجود ہے</b> پڑھتا ہے اور <b>منسوب</b> درجات ظاہر کرتا ہے — یہ تحقیقی معاون ہے، رجالی فیصلہ نہیں۔ نظام خود کسی راوی یا روایت کو درجہ نہیں دیتا۔',
  history_hint: 'آپ کے حالیہ جوابات، تقاریر اور موازنے — صرف اِس براؤزر میں محفوظ۔ فوری دیکھنے کے لیے <b>کھولیں</b> پر کلک کریں۔',
  clear_all: 'سب صاف کریں',
  query_lang: 'سوال کی زبان', caveats: 'انتباہات',
  filters: 'فلٹرز', restrict_sources: 'مآخذ محدود کریں', select_all: 'سب منتخب کریں', clear: 'صاف کریں',
  footer: 'شیعہ عالِم · جوابات تحقیق میں معاون ہیں، کسی مستند عالم (مرجع) کا نعم البدل نہیں۔ ہر حوالے کی اصل مأخذ سے تصدیق کریں۔',
  // dynamic labels used by the JS
  searching: 'تلاش جاری ہے…', building_outline: 'خاکہ تیار ہو رہا ہے…', comparing: 'موازنہ جاری ہے…',
  evidence_head: 'شواہد', click_passage: 'مکمل متن اور مأخذ کے لیے کسی اقتباس پر کلک کریں',
  details: 'تفصیل ›', open: 'کھولیں', del: 'حذف',
};
var uiLang = 'en', _origHTML = {}, _origPh = {};
// English defaults for labels generated in JS (not present in the static DOM).
var EN_DYN = {
  searching: 'Searching the corpus…', building_outline: 'Building the outline…', comparing: 'Comparing…',
  evidence_head: 'Evidence', click_passage: 'click a passage for full text & source details',
  details: 'details ›', open: 'Open', del: 'Delete', query_lang: 'Query language', caveats: 'Caveats',
};
function t(k){
  if(uiLang==='ur' && UR[k]!==undefined) return UR[k];
  if(_origHTML[k]!==undefined) return _origHTML[k];
  if(EN_DYN[k]!==undefined) return EN_DYN[k];
  return k;
}
function captureOrig(){
  document.querySelectorAll('[data-i18n]').forEach(function(el){ _origHTML[el.getAttribute('data-i18n')] = el.innerHTML; });
  document.querySelectorAll('[data-i18n-ph]').forEach(function(el){ _origPh[el.getAttribute('data-i18n-ph')] = el.getAttribute('placeholder'); });
}
function applyUiLang(l){
  uiLang = (l==='ur') ? 'ur' : 'en';
  try { localStorage.setItem('shia-ui-lang', uiLang); } catch(e){}
  document.documentElement.setAttribute('dir', uiLang==='ur' ? 'rtl' : 'ltr');
  document.documentElement.setAttribute('lang', uiLang);
  document.querySelectorAll('.ui-pill').forEach(function(p){ p.classList.toggle('active', p.dataset.uilang===uiLang); });
  document.querySelectorAll('[data-i18n]').forEach(function(el){
    var k = el.getAttribute('data-i18n');
    el.innerHTML = (uiLang==='ur' && UR[k]!==undefined) ? UR[k] : (_origHTML[k]!==undefined ? _origHTML[k] : el.innerHTML);
  });
  document.querySelectorAll('[data-i18n-ph]').forEach(function(el){
    var k = el.getAttribute('data-i18n-ph');
    var v = (uiLang==='ur' && UR[k]!==undefined) ? UR[k] : _origPh[k];
    if(v !== undefined) el.setAttribute('placeholder', v);
  });
}

function switchTab(name){
  document.querySelectorAll('.tab').forEach(t => t.classList.toggle('active', t.dataset.tab===name));
  ['ask','lecture','compare','rijal','history'].forEach(function(p){
    var el = document.getElementById('pane-'+p);
    if(el) el.style.display = (p===name) ? '' : 'none';
  });
  if(name==='rijal') loadRijalSummary();
}

function badge(kind, cls, label){ return '<span class="badge '+cls+'-'+kind+'">'+esc(label)+'</span>'; }

// ---- Citation detail drawer ----------------------------------------------
var drawerReg = {}, drawerSeq = 0;
function regDrawer(d){ var id = 'd'+(drawerSeq++); drawerReg[id] = d; return id; }

// A unified evidence "detail" from an answer claim or a lecture evidence item.
function detailFromClaim(c){
  var cit = (c.citations && c.citations[0]) || {};
  return {
    text: c.statement, arabic: cit.arabic_text || '',
    translation: cit.translation || '', translation_source: cit.translation_source || '',
    translation_ur: cit.translation_ur || '', translation_ur_source: cit.translation_ur_source || '',
    reference: refString(cit), confidence: c.confidence, evidence_type: c.evidence_type,
    view_status: c.view_status || null, grade: cit.grade || 'ungraded',
    grade_source: cit.grade_source || '', source_id: cit.source_id, locators: cit,
    asserted_as_fact: c.asserted_as_fact,
  };
}
function detailFromEv(ev){
  var cit = ev.citation || {};
  return {
    text: ev.text, arabic: cit.arabic_text || '',
    translation: ev.translation || cit.translation || '', translation_source: cit.translation_source || '',
    translation_ur: cit.translation_ur || '', translation_ur_source: cit.translation_ur_source || '',
    reference: ev.reference || refString(cit), confidence: ev.confidence, evidence_type: ev.evidence_type,
    view_status: ev.view_status || null, grade: cit.grade || 'ungraded',
    grade_source: cit.grade_source || '', source_id: cit.source_id, locators: cit,
    chain: ev.chain || null,   // narrator chain (rijāl view), if provided
  };
}

// Mirror of rijal.parse_grade_source for the drawer's Gradings block.
function parseGradeSource(gs){
  if(!gs) return [];
  return gs.split(';').map(function(p){
    p = p.trim(); if(!p) return null;
    var who = '', grade = p, work = '', ci = p.indexOf(':');
    if(ci >= 0){ who = p.slice(0,ci).trim(); var rest = p.slice(ci+1).trim(); grade = rest;
      var di = rest.indexOf(' - '); if(di >= 0){ grade = rest.slice(0,di).trim(); work = rest.slice(di+3).trim(); } }
    return { attributor: who, grade: grade, work: work };
  }).filter(Boolean);
}

function evidenceBlock(d){
  var conf = d.confidence || 'unverified';
  var type = d.evidence_type || '';
  var txt = d.text || d.arabic || '';
  var cls = isArabic(txt) ? 'txt ar' : 'txt';
  var trans = (d.translation && d.translation !== txt)
    ? '<p class="txt" style="color:var(--muted);font-size:13.5px">'+esc(d.translation)+'</p>' : '';
  var ur = d.translation_ur ? '<p class="txt ur-inline">'+esc(d.translation_ur)+'</p>' : '';
  var id = regDrawer(d);
  return '<div class="ev clickable" data-d="'+id+'" onclick="openDrawer(drawerReg[this.dataset.d])" '+
    'title="View full passage &amp; source details"><p class="'+cls+'">'+esc(txt)+'</p>'+trans+ur+
    '<div class="badges">'+badge(type,'t',type.replace(/_/g,' '))+badge(conf,'b',conf)+
    '<span class="ref">'+esc(d.reference || '')+'<span class="more">'+t('details')+'</span></span></div></div>';
}

function locatorRows(cit){
  var rows = [];
  function add(k,v){ if(v!==undefined && v!==null && v!=='') rows.push('<div class="k">'+k+'</div><div class="v">'+esc(v)+'</div>'); }
  add('Surah:Ayah', cit.surah ? cit.surah+':'+cit.ayah : '');
  add('Volume', cit.volume); add('Page', cit.page);
  add('Hadith no.', cit.hadith_number); add('Chapter', cit.chapter);
  return rows.join('');
}

function openDrawer(d){
  if(!d) return;
  var title = (sourceTitles[d.source_id] || d.source_id || 'Passage');
  document.getElementById('drawerTitle').textContent = title;
  var h = '<div class="src">'+esc(d.reference || '')+'</div>';
  h += '<div class="badges" style="margin:10px 0 4px">'+
       badge(d.evidence_type||'', 't', (d.evidence_type||'').replace(/_/g,' '))+
       badge(d.confidence||'unverified','b',d.confidence||'unverified')+
       (d.view_status ? '<span class="badge" style="background:var(--unverified)">'+esc(d.view_status.replace(/_/g,' '))+'</span>' : '')+
       '</div>';
  if(d.arabic) h += '<div class="grp"><div class="ar">'+esc(d.arabic)+'</div></div>';
  if(d.text)   h += '<div class="grp"><div class="k">Text</div><div class="en">'+esc(d.text)+'</div></div>';
  if(d.translation && d.translation !== d.text)
    h += '<div class="grp"><div class="k">Translation</div><div class="en">'+esc(d.translation)+'</div></div>';
  if(d.translation_ur)
    h += '<div class="grp"><div class="k">اردو ترجمہ · Urdu translation</div><div class="ur">'+esc(d.translation_ur)+'</div>'+
         (d.translation_ur_source ? '<div class="src">— '+esc(d.translation_ur_source)+'</div>' : '')+'</div>';
  if(d.translation_source)
    h += '<div class="grp"><div class="k">Translation source</div><div class="v">'+esc(d.translation_source)+'</div></div>';
  // Transmission chain (rijāl) — a surface reading of the text, clearly caveated.
  if(d.chain && d.chain.length){
    h += '<div class="grp"><div class="k">Transmission chain — as it appears in the text</div>'+
         '<div class="chain">'+d.chain.map(function(n,i){
           return '<span class="cn">'+esc(n)+'</span>'+(i<d.chain.length-1?'<span class="carrow">→</span>':'');
         }).join('')+'</div>'+
         '<div class="src" style="margin-top:4px">Heuristically parsed from the narration text — a surface reading, not a verified isnad or a rijāl evaluation.</div></div>';
  }
  // Gradings — surfaced from the attributable grade_source; never derived here.
  var attrs = parseGradeSource((d.locators||{}).grade_source);
  if(attrs.length){
    h += '<div class="grp"><div class="k">Gradings (ʿilm al-rijāl) — attributed</div>'+
      attrs.map(function(a){
        return '<div class="grade-attr"><span class="ga-grade">'+esc(a.grade)+'</span> '+
          (a.attributor ? '<span class="ga-who">'+esc(a.attributor)+'</span>' : '')+
          (a.work ? ' <span class="src">· '+esc(a.work)+'</span>' : '')+'</div>';
      }).join('')+'</div>';
  } else if(d.grade && d.grade !== 'ungraded'){
    h += '<div class="grp"><div class="k">Grade (ʿilm al-rijāl)</div><div class="v">'+esc(d.grade)+'</div></div>';
  } else if((d.evidence_type||'')==='hadith'){
    h += '<div class="grp src">Ungraded here — no attributable grade is recorded for this narration.</div>';
  }
  var loc = locatorRows(d.locators||{});
  if(loc) h += '<div class="grp"><div class="k">Locators</div><div class="kv" style="margin-top:6px">'+loc+'</div></div>';
  if(d.asserted_as_fact !== undefined)
    h += '<div class="grp src">'+(d.asserted_as_fact
      ? 'Backed by a complete citation at fact-level confidence.'
      : 'Not asserted as established fact — treat as evidence to weigh, not a settled ruling.')+'</div>';
  // For a Qur'an verse, offer to pull its tafsir + related narrations.
  var loc = d.locators || {};
  if((d.evidence_type||'') === 'quran' && loc.surah != null && loc.ayah != null){
    h += '<div class="grp"><button class="mini xref-btn" onclick="loadCrossref('+loc.surah+','+loc.ayah+')">⋈ Find related tafsir &amp; narrations</button>'+
         '<div id="crossrefOut"></div></div>';
  }
  h += '<div class="grp src">Verify against the primary source before relying on it.</div>';
  document.getElementById('drawerBody').innerHTML = h;
  document.getElementById('drawer').classList.add('open');
  document.getElementById('drawer').setAttribute('aria-hidden','false');
  document.getElementById('drawerOverlay').classList.add('open');
}
function closeDrawer(){
  document.getElementById('drawer').classList.remove('open');
  document.getElementById('drawer').setAttribute('aria-hidden','true');
  document.getElementById('drawerOverlay').classList.remove('open');
}
document.addEventListener('keydown', function(e){ if(e.key==='Escape') closeDrawer(); });

// ---- Cross-references: verse -> tafsir + related narrations ----------------
async function loadCrossref(surah, ayah){
  var out = document.getElementById('crossrefOut'); if(!out) return;
  out.innerHTML = '<div class="spinner" style="padding:10px 0">Finding related tafsir &amp; narrations</div>';
  try {
    var res = await fetch('/api/crossref', {method:'POST', headers:{'Content-Type':'application/json'},
      body: JSON.stringify({surah:surah, ayah:ayah, embedder:selectedEmbedder()})});
    var data = await res.json();
    if(data.error){ out.innerHTML = '<div class="empty" style="padding:8px 0">'+esc(data.error)+'</div>'; return; }
    out.innerHTML = crossrefSections(data);
  } catch(e){ out.innerHTML = '<div class="empty" style="padding:8px 0">Request failed: '+esc(e.message)+'</div>'; }
}
function crossrefSection(title, items){
  if(!items || !items.length) return '';
  return '<div class="grp"><div class="k">'+title+' ('+items.length+')</div>'+
    items.map(function(ev){ return crossrefRow(detailFromEv(ev), ev.link_type); }).join('')+'</div>';
}
function crossrefSections(data){
  var html = crossrefSection('Tafsir', data.tafsir) +
             crossrefSection('Related narrations', data.hadith) +
             crossrefSection('Related verses', data.verses);
  return html || '<div class="empty" style="padding:8px 0">No related tafsir or narrations found in the corpus for this verse.</div>';
}
function crossrefRow(d, linkType){
  var id = regDrawer(d);
  var conf = d.confidence || 'unverified', type = d.evidence_type || '';
  var txt = d.text || d.arabic || '';
  var cls = isArabic(txt) ? 'txt ar' : 'txt';
  return '<div class="ev clickable" data-d="'+id+'" onclick="openDrawer(drawerReg[this.dataset.d])" style="margin-top:8px" '+
    'title="Open this passage">'+
    '<p class="'+cls+'">'+esc(txt)+'</p><div class="badges">'+
    '<span class="linktag lt-'+esc(linkType)+'">'+esc(linkType)+'</span>'+
    badge(type,'t',type.replace(/_/g,' '))+badge(conf,'b',conf)+
    '<span class="ref">'+esc(d.reference || '')+'</span></div></div>';
}

// ---- Rijāl / narrator lookup ----------------------------------------------
var rijalLoaded = false;
function gradeDist(dist){
  var keys = Object.keys(dist||{});
  if(!keys.length) return '';
  return '<div class="grade-dist">'+keys.map(function(g){
    return '<span class="gpill">'+esc(g)+' <b>'+dist[g]+'</b></span>';
  }).join('')+'</div>';
}
function loadRijalSummary(){
  if(rijalLoaded) return;
  rijalLoaded = true;
  var box = document.getElementById('rijalSummary');
  box.innerHTML = '<div class="spinner">Reading chains &amp; gradings</div>';
  fetch('/api/rijal/summary').then(r=>r.json()).then(function(s){
    if(!s.hadith){ box.innerHTML = '<div class="empty">No hadith in the loaded corpus, so there are no chains to read.</div>'; return; }
    var h = '<div class="evhead">Corpus gradings</div>'+
      '<p class="subq">'+s.hadith.toLocaleString()+' narrations · '+s.with_readable_chain.toLocaleString()+
      ' with a readable chain · '+s.narrator_count.toLocaleString()+' distinct narrators (surface reading)</p>'+
      gradeDist(s.grades);
    if((s.attributors||[]).length){
      h += '<div class="evhead" style="margin-top:16px">Grade attributors</div>'+
        '<div class="nchips">'+s.attributors.slice(0,12).map(function(a){
          return '<span class="gpill">'+esc(a.attributor)+' <b>'+a.total+'</b></span>';
        }).join('')+'</div>';
    }
    if((s.top_narrators||[]).length){
      h += '<div class="evhead" style="margin-top:16px">Most frequent narrators <span class="idxnote">click to look up</span></div>'+
        '<div class="nchips">'+s.top_narrators.map(function(n){
          return '<span class="nchip" onclick="lookupNarratorName(\''+esc(n.name.replace(/\\/g,"").replace(/'/g,"\\'"))+'\')">'+
            esc(n.name)+'<span class="cnt">'+n.count+'</span></span>';
        }).join('')+'</div>';
    }
    box.innerHTML = h;
  }).catch(function(){ box.innerHTML = '<div class="empty">Could not load the narrator index.</div>'; });
}
function lookupNarratorName(name){
  document.getElementById('rq').value = name;
  switchTab('rijal');
  lookupNarrator();
}
async function lookupNarrator(){
  var name = document.getElementById('rq').value.trim();
  if(!name) return;
  var box = document.getElementById('rijalResult');
  var btn = document.getElementById('rqBtn');
  btn.disabled = true; box.innerHTML = spinner('Searching chains for “'+esc(name)+'”…');
  try {
    var res = await fetch('/api/rijal/narrator', {method:'POST', headers:{'Content-Type':'application/json'}, body: JSON.stringify({name:name})});
    var data = await res.json();
    if(data.error){ box.innerHTML = '<div class="empty">'+esc(data.error)+'</div>'; return; }
    renderNarrator(box, data);
  } catch(e){ box.innerHTML = '<div class="empty">Request failed: '+esc(e.message)+'</div>'; }
  finally { btn.disabled = false; }
}
function renderNarrator(box, data){
  if(!data.narration_count){
    box.innerHTML = '<div class="empty">No narration chain in the corpus mentions “'+esc(data.query)+'”. '+
      'Note the chain reading is a surface heuristic; try a different spelling (e.g. Ibn vs Bin).</div>';
    return;
  }
  var names = (data.matched_names||[]).slice(0,6).join(', ');
  var h = '<div class="qtitle">'+esc(data.query)+'</div>'+
    '<p class="subq">Appears in <b>'+data.narration_count+'</b> narration'+(data.narration_count>1?'s':'')+
    '\'s chain'+(names ? ' · matched: '+esc(names) : '')+'. Click a narration for its full chain &amp; gradings.</p>'+
    gradeDist(data.grade_distribution)+
    '<div class="evhead" style="margin-top:14px">Narrations</div>'+
    (data.narrations||[]).map(function(n){ return evidenceBlock(detailFromEv(n)); }).join('');
  box.innerHTML = h;
}

function refString(cit){
  if(!cit) return '';
  if(cit.evidence_type==='quran' && cit.surah) return "Qur'an "+cit.surah+':'+cit.ayah;
  var p=[cit.source_id];
  if(cit.volume) p.push('v'+cit.volume);
  if(cit.page) p.push('p.'+cit.page);
  if(cit.hadith_number) p.push('h.'+cit.hadith_number);
  if(cit.chapter) p.push('ch.'+cit.chapter);
  return p.filter(Boolean).join(', ');
}

// Last-rendered Markdown per tab, for the copy / download buttons.
var lastMd = { ask: {text:'', name:'answer'}, lec: {text:'', name:'lecture'}, cmp: {text:'', name:'compare'} };
function slug(s){ return (s||'shia-aalim').toLowerCase().replace(/[^a-z0-9]+/g,'-').replace(/^-|-$/g,'').slice(0,60) || 'shia-aalim'; }
function selectedEmbedder(){ var el = document.getElementById('embedder'); return el && el.value ? el.value : null; }
function showTools(tab){ document.getElementById(tab+'Tools').classList.remove('hidden'); }
function hideTools(tab){ document.getElementById(tab+'Tools').classList.add('hidden'); }

var embedderStates = {};   // spec -> 'ready' | 'lazy' | 'failed', from /api/status
// Choose the waiting message: an index that hasn't been built yet ('lazy') can
// take a while on a large corpus, so say so instead of a bare "Searching…".
function spinner(base){
  var spec = selectedEmbedder();
  if(spec && embedderStates[spec] === 'lazy'){
    return '<div class="spinner building">Building the <code>'+esc(spec)+
      '</code> index for the first time — on a large corpus this can take a minute. '+
      'It is cached, so later queries are fast</div>';
  }
  return '<div class="spinner">'+base+'</div>';
}

// ---- Session history (localStorage) ---------------------------------------
var HKEY = 'shia-aalim-history', HMAX = 30;
var qhistory = loadHistory();   // NB: not `history` — that shadows window.history
var HTYPE = { ask:'Answer', lecture:'Lecture', compare:'Compare' };

function loadHistory(){ try { return JSON.parse(localStorage.getItem(HKEY) || '[]'); } catch(e){ return []; } }
function saveHistory(){ try { localStorage.setItem(HKEY, JSON.stringify(qhistory.slice(0, HMAX))); } catch(e){} }
function pushHistory(type, label, data){
  qhistory.unshift({ id: 'h'+Date.now()+'-'+Math.floor(Math.random()*1e4), type:type, label:label, ts:new Date().toISOString(), data:data });
  qhistory = qhistory.slice(0, HMAX);
  saveHistory(); renderHistory();
}
function fmtTime(iso){ try { return new Date(iso).toLocaleString(); } catch(e){ return iso; } }

function renderHistory(){
  var box = document.getElementById('historyList'); if(!box) return;
  if(!qhistory.length){ box.innerHTML = '<div class="empty">No history yet — ask a question, build a lecture, or run a comparison.</div>'; return; }
  box.innerHTML = qhistory.map(function(h){
    return '<div class="hitem"><div class="hmeta">'+
      '<span class="htype ht-'+h.type+'">'+esc(HTYPE[h.type]||h.type)+'</span>'+
      '<span class="hlabel">'+esc(h.label)+'</span><span class="htime">'+esc(fmtTime(h.ts))+'</span></div>'+
      '<div class="hact"><button class="fmini" onclick="restoreHistory(\''+h.id+'\')">'+t('open')+'</button>'+
      '<button class="fmini" onclick="deleteHistory(\''+h.id+'\')">'+t('del')+'</button></div></div>';
  }).join('');
}
function restoreHistory(id){
  var h = qhistory.filter(function(x){ return x.id===id; })[0]; if(!h) return;
  if(h.type==='ask'){
    switchTab('ask'); renderAnswer(document.getElementById('askResult'), h.data.answer);
    lastMd.ask = { text:h.data.markdown||'', name:h.data.answer.question }; showTools('ask');
  } else if(h.type==='lecture'){
    switchTab('lecture'); renderLecture(document.getElementById('lecResult'), h.data);
    lastMd.lec = { text:h.data.markdown||'', name:h.data.topic }; showTools('lec');
  } else if(h.type==='compare'){
    switchTab('compare'); renderCompare(document.getElementById('cmpResult'), h.data);
    lastMd.cmp = { text:compareMarkdown(h.data), name:'compare-'+h.data.question }; showTools('cmp');
  }
}
function deleteHistory(id){ qhistory = qhistory.filter(function(x){ return x.id!==id; }); saveHistory(); renderHistory(); }
function clearHistory(){ qhistory = []; saveHistory(); renderHistory(); }

// ---- Filters (evidence type, source book, minimum confidence) -------------
function checked(containerId){
  return Array.prototype.slice.call(document.querySelectorAll('#'+containerId+' input:checked'))
    .map(function(i){ return i.value; });
}
function selectedTypes(prefix){ var v = checked(prefix+'Types'); return v.length ? v : null; }
function selectedSources(prefix){ var v = checked(prefix+'Sources'); return v.length ? v : null; }

function filterSrcList(prefix, q){
  q = (q||'').toLowerCase();
  document.querySelectorAll('#'+prefix+'Sources label.chk').forEach(function(l){
    l.style.display = l.dataset.search.indexOf(q) >= 0 ? '' : 'none';
  });
}
function setAllSrc(prefix, val){
  document.querySelectorAll('#'+prefix+'Sources label.chk').forEach(function(l){
    if(l.style.display !== 'none') l.querySelector('input').checked = val;  // only visible rows
  });
  updateFilterCount(prefix);
}
function setCount(id, txt){ var el = document.getElementById(id); if(el) el.textContent = txt; }
function updateFilterCount(prefix){
  if(prefix === 'ask'){
    var n = checked('askTypes').length + checked('askSources').length;
    var conf = document.getElementById('askConf');
    if(conf && conf.value !== 'low') n += 1;   // 'low' is the default floor
    setCount('askFilterCount', n ? '· '+n+' active' : '');
  } else {
    var m = checked(prefix+'Sources').length;
    setCount(prefix+'FilterCount', m ? '· '+m+' book'+(m>1?'s':'') : '');
  }
}

function srcRow(prefix, s){
  var dot = s.confidence ? '<span class="cdot cdot-'+esc(s.confidence)+'" title="'+esc(s.confidence)+' confidence"></span>' : '';
  var search = (s.title+' '+s.id).toLowerCase();
  return '<label class="chk" data-search="'+esc(search)+'">'+
    '<input type="checkbox" value="'+esc(s.id)+'" onchange="updateFilterCount(\''+prefix+'\')">'+
    dot+esc(s.title)+'<span class="cnt">'+s.count.toLocaleString()+'</span></label>';
}
function typeRow(t){
  var label = t.type.replace(/_/g,' ');
  return '<label class="chk"><input type="checkbox" value="'+esc(t.type)+'" onchange="updateFilterCount(\'ask\')"> '+
    esc(label)+'<span class="cnt">'+t.count.toLocaleString()+'</span></label>';
}

var sourceTitles = {};   // source_id -> human title, for the drawer header
function loadFacets(){
  return fetch('/api/sources').then(r=>r.json()).then(function(f){
    (f.sources||[]).forEach(function(s){ sourceTitles[s.id] = s.title; });
    document.getElementById('askTypes').innerHTML = (f.evidence_types||[]).map(typeRow).join('') || '<span class="idxnote">none</span>';
    var srcHtml = function(prefix){ return (f.sources||[]).map(function(s){ return srcRow(prefix, s); }).join(''); };
    document.getElementById('askSources').innerHTML = srcHtml('ask');
    document.getElementById('lecSources').innerHTML = srcHtml('lec');
    document.getElementById('cmpSources').innerHTML = srcHtml('cmp');
  }).catch(function(){
    document.getElementById('askTypes').innerHTML = '<span class="idxnote">unavailable</span>';
  });
}

async function copyMd(tab){
  var md = lastMd[tab].text; if(!md) return;
  try { await navigator.clipboard.writeText(md); flash(tab, 'Copied ✓'); }
  catch(e){
    var ta = document.createElement('textarea'); ta.value = md; document.body.appendChild(ta);
    ta.select(); try { document.execCommand('copy'); flash(tab,'Copied ✓'); } catch(_){}
    document.body.removeChild(ta);
  }
}
function downloadMd(tab){
  var md = lastMd[tab].text; if(!md) return;
  var blob = new Blob([md], {type:'text/markdown;charset=utf-8'});
  var url = URL.createObjectURL(blob);
  var a = document.createElement('a');
  a.href = url; a.download = slug(lastMd[tab].name) + '.md';
  document.body.appendChild(a); a.click(); document.body.removeChild(a);
  URL.revokeObjectURL(url);
}
function flash(tab, msg){
  var btn = document.querySelector('#'+tab+'Tools button'); if(!btn) return;
  var old = btn.textContent; btn.textContent = msg;
  setTimeout(function(){ btn.textContent = old; }, 1200);
}

async function ask(){
  var q = document.getElementById('q').value.trim();
  if(!q) return;
  var k = document.getElementById('k').value;
  var box = document.getElementById('askResult');
  var btn = document.getElementById('askBtn');
  btn.disabled = true; hideTools('ask'); box.innerHTML = spinner(t('searching'));
  try {
    var res = await fetch('/api/answer', {method:'POST', headers:{'Content-Type':'application/json'}, body: JSON.stringify({
      question:q, k:Number(k), embedder:selectedEmbedder(),
      evidence_types: selectedTypes('ask'), source_ids: selectedSources('ask'),
      min_confidence: document.getElementById('askConf').value,
      answer_language: answerLang
    })});
    var data = await res.json();
    if(data.error){ box.innerHTML = '<div class="empty">'+esc(data.error)+'</div>'; return; }
    renderAnswer(box, data.answer);
    lastMd.ask = { text: data.markdown || '', name: data.answer.question };
    showTools('ask');
    pushHistory('ask', data.answer.question, {answer: data.answer, markdown: data.markdown});
  } catch(e){ box.innerHTML = '<div class="empty">Request failed: '+esc(e.message)+'</div>'; }
  finally { btn.disabled = false; refreshStatus(); }
}

var LANG_NAME = { ar:'Arabic', fa:'Persian', ur:'Urdu', en:'English' };
var answerLang = 'en';
function setAnswerLang(l){
  answerLang = l;
  document.querySelectorAll('#langSel .lang-pill').forEach(function(p){ p.classList.toggle('active', p.dataset.lang===l); });
  var note = document.getElementById('langNote');
  note.textContent = (l==='en') ? '' : 'AI translates the answer from the cited English/Arabic evidence, then verifies it.';
}
function renderAnswer(box, a){
  var h = '<div class="qtitle">'+esc(a.question)+'</div>';
  if(a.refined_query)
    h += '<p class="subq">Interpreted as: <b>'+esc(a.refined_query)+'</b></p>';
  if(a.query_language && a.query_language !== 'en' && a.query_language !== 'unknown')
    h += '<p class="subq">'+t('query_lang')+': <b>'+esc(LANG_NAME[a.query_language] || a.query_language)+'</b></p>';
  if(a.sub_questions && a.sub_questions.length)
    h += '<p class="subq">Decomposed into: '+a.sub_questions.map(esc).join(' · ')+'</p>';
  if(a.summary){
    var isRtl = (a.answer_language === 'ur' || a.answer_language === 'ar');
    var lbl = isRtl ? ('AI answer in '+(LANG_NAME[a.answer_language]||'')+' — translated from the evidence &amp; verified')
                    : 'Synthesized answer — AI prose, verified against the evidence below';
    h += '<div class="summary'+(isRtl?' rtl':'')+'"><div class="lbl">'+lbl+'</div>'+esc(a.summary)+'</div>';
  }
  if(!a.claims || !a.claims.length){
    h += '<div class="empty">No sufficiently-relevant evidence was found in the knowledge base for this question.</div>';
  } else {
    h += '<div class="evhead">'+t('evidence_head')+' ('+a.claims.length+') · <span class="idxnote">'+t('click_passage')+'</span></div>';
    h += a.claims.map(c => evidenceBlock(detailFromClaim(c))).join('');
  }
  if(a.caveats && a.caveats.length)
    h += '<div class="caveats"><div class="lbl">'+t('caveats')+'</div><ul>'+a.caveats.map(c=>'<li>'+esc(c)+'</li>').join('')+'</ul></div>';
  box.innerHTML = h;
}

async function lecture(){
  var t = document.getElementById('topic').value.trim();
  if(!t) return;
  var depth = document.getElementById('depth').value;
  var box = document.getElementById('lecResult');
  var btn = document.getElementById('lecBtn');
  btn.disabled = true; hideTools('lec'); box.innerHTML = spinner(t('building_outline'));
  try {
    var res = await fetch('/api/lecture', {method:'POST', headers:{'Content-Type':'application/json'}, body: JSON.stringify({
      topic:t, depth:Number(depth), embedder:selectedEmbedder(), source_ids: selectedSources('lec')
    })});
    var data = await res.json();
    if(data.error){ box.innerHTML = '<div class="empty">'+esc(data.error)+'</div>'; return; }
    renderLecture(box, data);
    lastMd.lec = { text: data.markdown || '', name: data.topic };
    showTools('lec');
    pushHistory('lecture', data.topic, data);
  } catch(e){ box.innerHTML = '<div class="empty">Request failed: '+esc(e.message)+'</div>'; }
  finally { btn.disabled = false; refreshStatus(); }
}

async function compare(){
  var q = document.getElementById('cq').value.trim();
  if(!q) return;
  var sources = selectedSources('cmp');
  var box = document.getElementById('cmpResult');
  if(!sources){ box.innerHTML = '<div class="empty">Select at least one book to compare (use the list above).</div>'; return; }
  var k = document.getElementById('ck').value;
  var btn = document.getElementById('cmpBtn');
  btn.disabled = true; hideTools('cmp');
  box.innerHTML = spinner(t('comparing'));
  try {
    var res = await fetch('/api/compare', {method:'POST', headers:{'Content-Type':'application/json'}, body: JSON.stringify({
      question:q, sources:sources, k:Number(k), embedder:selectedEmbedder()
    })});
    var data = await res.json();
    if(data.error){ box.innerHTML = '<div class="empty">'+esc(data.error)+'</div>'; return; }
    renderCompare(box, data);
    lastMd.cmp = { text: compareMarkdown(data), name: 'compare-'+q };
    showTools('cmp');
    pushHistory('compare', q + ' (' + (data.columns||[]).length + ' books)', data);
  } catch(e){ box.innerHTML = '<div class="empty">Request failed: '+esc(e.message)+'</div>'; }
  finally { btn.disabled = false; refreshStatus(); }
}

function renderCompare(box, data){
  var h = '<div class="qtitle">'+esc(data.question)+'</div>'+
    '<p class="subq">Same question, each book answered on its own evidence. Click any passage for details.'+
    (data.truncated ? ' <b>(limited to the first 6 books)</b>' : '')+'</p>';
  h += '<div class="cols">' + (data.columns||[]).map(function(col){
    var claims = (col.answer && col.answer.claims) || [];
    var out = '<div class="col"><h4>'+esc(col.title)+'</h4>'+
      '<div class="meta">'+(claims.length ? claims.length+' passage'+(claims.length>1?'s':'') : 'no matching evidence')+'</div>';
    out += claims.length
      ? claims.map(c => evidenceBlock(detailFromClaim(c))).join('')
      : '<div class="empty">Nothing in this book cleared the bar for the question.</div>';
    return out + '</div>';
  }).join('') + '</div>';
  box.innerHTML = h;
}

function compareMarkdown(data){
  var lines = ['# Compare — '+data.question, ''];
  (data.columns||[]).forEach(function(col){
    lines.push('## '+col.title);
    var claims = (col.answer && col.answer.claims) || [];
    if(!claims.length){ lines.push('', '_No matching evidence._', ''); return; }
    lines.push('');
    claims.forEach(function(c){
      var cit = (c.citations && c.citations[0]) || {};
      lines.push('- **['+c.evidence_type+' · '+String(c.confidence).toUpperCase()+']** '+c.statement);
      lines.push('  — _'+refString(cit)+'_');
    });
    lines.push('');
  });
  return lines.join('\n');
}

function renderLecture(box, L){
  var h = '<div class="qtitle">'+esc(L.topic)+'</div><p class="subq">Outline generated '+esc(L.generated_on)+'. Verify every citation before delivery.</p>';
  h += L.sections.map(s => {
    var out = '<div class="sec"><h3>'+esc(s.title)+(s.synthesized?' <span class="synth">✓ synthesized &amp; verified</span>':'')+'</h3>';
    if(s.body) out += '<div class="body">'+esc(s.body)+'</div>';
    out += s.evidence.map(function(ev){ return evidenceBlock(detailFromEv(ev)); }).join('');
    if(s.note) out += '<div class="note">Lecturer note: '+esc(s.note)+'</div>';
    return out + '</div>';
  }).join('');
  box.innerHTML = h;
}

function stateTag(st){ return st==='ready' ? '' : st==='failed' ? ' (unavailable)' : ' — builds on first use'; }

function onEmbedderChange(){
  var el = document.getElementById('embedder');
  var st = el.options[el.selectedIndex] ? el.options[el.selectedIndex].dataset.state : 'ready';
  document.getElementById('idxnote').textContent =
    st==='lazy' ? 'This index will be built the first time you query it.' :
    st==='failed' ? 'This index failed to build in this environment; queries will report the reason.' : '';
}

function applyStatus(s){
  var sel = document.getElementById('embedder');
  var cur = sel.value;
  embedderStates = {};
  (s.embedders||[]).forEach(function(e){ embedderStates[e.spec] = e.state; });
  sel.innerHTML = (s.embedders||[]).map(function(e){
    return '<option value="'+esc(e.spec)+'" data-state="'+esc(e.state)+'"'+(e.default?' selected':'')+'>'+
      esc(e.spec)+stateTag(e.state)+'</option>';
  }).join('');
  if(cur && embedderStates[cur] !== undefined) sel.value = cur;   // keep the user's choice
  sel.disabled = (s.embedders||[]).length < 2;   // nothing to switch between
  onEmbedderChange();

  // Reflect the server's default evidence count in the input (once), so the
  // user isn't stuck at the old hardcoded value. They can still dial it (up to 25).
  if(!window._kInit && s.default_k){ var ke=document.getElementById('k'); if(ke) ke.value = s.default_k; window._kInit = true; }
  // Reveal the answer-language picker only when AI synthesis is actually live.
  var ai = s.ai || {};
  document.getElementById('langSel').style.display = ai.synthesis ? '' : 'none';
  if(ai.synthesis && !ai.translate){
    // synthesis on but no cross-lingual verifier -> Urdu/Arabic can't be verified
    document.querySelectorAll('#langSel .lang-pill[data-lang="ur"],#langSel .lang-pill[data-lang="ar"]').forEach(function(p){
      p.title = 'Needs an AI verifier (JUDGE=claude) to check translations';
    });
  }
  var aiBits = [];
  if(ai.synthesis) aiBits.push('AI answers');
  if(ai.refine) aiBits.push('spell-check');
  if(ai.translate) aiBits.push('translation');
  var aiTxt = aiBits.length ? ' · <span style="color:var(--accent)">'+aiBits.join(' + ')+' on</span>' : '';
  document.getElementById('status').innerHTML =
    'Corpus: <b>'+s.documents.toLocaleString()+'</b> documents · index <code>'+esc(s.default_embedder)+'</code>'+aiTxt;
  if((s.provider_notes||[]).length)
    document.getElementById('status').innerHTML += '<br><span style="color:var(--low)">'+s.provider_notes.map(esc).join('; ')+'</span>';
}

function refreshStatus(){
  return fetch('/api/status').then(r=>r.json()).then(applyStatus)
    .catch(()=>{ document.getElementById('status').textContent = ''; });
}

captureOrig();
try { applyUiLang(localStorage.getItem('shia-ui-lang') || 'en'); } catch(e) { applyUiLang('en'); }
refreshStatus();
loadFacets();
renderHistory();
</script>
</body>
</html>
"""


# ---------------------------------------------------------------------------
# CLI
# ---------------------------------------------------------------------------


def main(argv: Optional[list[str]] = None) -> int:
    parser = argparse.ArgumentParser(
        description="Serve the Shia-Aalim web front-end (FastAPI + uvicorn).",
        formatter_class=argparse.RawDescriptionHelpFormatter,
    )
    # Defaults come from the environment first so a container/PaaS can configure
    # the server without changing the command (HOST/PORT/KNOWLEDGE_DIR/EMBEDDER).
    parser.add_argument("--host", default=os.environ.get("HOST", "127.0.0.1"))
    parser.add_argument("--port", type=int, default=int(os.environ.get("PORT", "8000")))
    parser.add_argument("--knowledge-dir",
                        default=os.environ.get("KNOWLEDGE_DIR", str(DEFAULT_KNOWLEDGE_DIR)))
    parser.add_argument("--registry", default=str(DEFAULT_REGISTRY))
    parser.add_argument(
        "--embedder", default=os.environ.get("EMBEDDER", "tfidf"),
        help="one or a comma-separated list to offer as a UI toggle; the first is "
        "the default (e.g. 'tfidf' or 'tfidf,st:BAAI/bge-m3'). tfidf | hashing | st:<model>",
    )
    parser.add_argument("--synthesize", default=os.environ.get("SYNTHESIZE", "none"),
                        help="none | mock | claude:<model> (env: SYNTHESIZE; needs ANTHROPIC_API_KEY)")
    parser.add_argument("--judge", default=os.environ.get("JUDGE", "lexical"),
                        help="lexical | mock | claude:<model> (env: JUDGE)")
    parser.add_argument("--decompose", default=os.environ.get("DECOMPOSE", "none"),
                        help="none | rule | claude:<model> (env: DECOMPOSE)")
    parser.add_argument("--refine", default=os.environ.get("REFINE", "none"),
                        help="AI query correction: none | mock | claude:<model> (env: REFINE)")
    parser.add_argument("--k", type=int, default=int(os.environ.get("K", "8")),
                        help="default evidence passages per answer (env: K)")
    args = parser.parse_args(argv)

    try:
        import uvicorn
    except ImportError:
        print(_FASTAPI_HINT, file=sys.stderr)
        return 1

    embedders = [s.strip() for s in args.embedder.split(",") if s.strip()] or ["tfidf"]
    cache_env = os.environ.get("INDEX_CACHE_DIR")
    config = AppConfig(
        knowledge_dir=Path(args.knowledge_dir),
        registry_path=Path(args.registry),
        embedders=embedders,
        synthesize=args.synthesize,
        judge=args.judge,
        decompose=args.decompose,
        refine=args.refine,
        default_k=args.k,
        cache_dir=Path(cache_env) if cache_env else None,
    )
    print(f"Loading corpus from {config.knowledge_dir} …", file=sys.stderr)
    app = create_app(config)
    n = app.state.stack.n_documents
    extra = [e for e in embedders[1:]]
    switch = f" (+{', '.join(extra)} on first use)" if extra else ""
    print(
        f"Loaded {n:,} documents; default index '{config.default_embedder}' ready{switch}. "
        f"Serving Shia-Aalim on http://{args.host}:{args.port}",
        file=sys.stderr,
    )
    uvicorn.run(app, host=args.host, port=args.port)
    return 0


if __name__ == "__main__":
    raise SystemExit(main())
