"""Local web front-end for Shia-Aalim (FastAPI).

This wraps the *same* :class:`~shia_aalim.generation.answer.AnswerGenerator` and
:class:`~shia_aalim.generation.lecture.LectureGenerator` that ``scripts/demo.py``
uses in a tiny HTTP API plus a single self-contained HTML page, so the assistant
can be used in a browser instead of the terminal.

Nothing here weakens the charter guarantees. The web layer only *presents* what
the pipeline produces: answers are generated by the exact same grounded
retrieval + verification path, every claim still carries its citation and
confidence, and the grounding firewall still withholds anything it can't verify.
The browser just renders that structured output.

    pip install -e ".[web]"          # fastapi + uvicorn
    python -m shia_aalim.web         # serve on http://127.0.0.1:8000

FastAPI/uvicorn are optional extras; importing this module (or calling
:func:`create_app`) without them raises a clear install hint rather than a bare
``ImportError``. The corpus is loaded once at startup; each configured embedder's
index is built lazily on first use (the default is built at startup so the
corpus is validated), so the front-end runs anywhere the CLI does and a
switchable semantic embedder that isn't reachable degrades to a clear message
rather than crashing the server.
"""

from __future__ import annotations

import argparse
import sys
from dataclasses import dataclass, field
from pathlib import Path
from typing import Optional

from .generation.answer import AnswerGenerator
from .generation.decompose import make_decomposer
from .generation.lecture import Lecture, LectureGenerator
from .generation.synthesizer import make_synthesizer
from .grounding.entailment import make_judge
from .ingestion.loaders import iter_knowledge_dir
from .models import Answer, ConfidenceLevel, Document, EvidenceType, Source
from .research_loop import build_index
from .retrieval.embeddings import make_embedder
from .sources import load_registry_ids, load_sources

ROOT = Path(__file__).resolve().parent.parent.parent
DEFAULT_KNOWLEDGE_DIR = ROOT / "data" / "knowledge"
DEFAULT_REGISTRY = ROOT / "data" / "sources" / "registry.yaml"

_FASTAPI_HINT = (
    "The web front-end needs FastAPI and uvicorn, which are optional extras.\n"
    "Install them with:\n\n    pip install -e \".[web]\"\n\n"
    "(or: pip install fastapi uvicorn). The CLI — scripts/demo.py — needs no extras."
)

# Request body models live at *module* level (not inside create_app): with
# ``from __future__ import annotations`` in effect, FastAPI resolves endpoint
# annotations against the function's module globals, so a locally-scoped model
# would silently be misread as a query parameter. Pydantic ships with FastAPI;
# guard the import so merely importing this module never hard-requires the extra.
try:
    from pydantic import BaseModel as _BaseModel

    class AskBody(_BaseModel):
        question: str = ""
        k: Optional[int] = None
        embedder: Optional[str] = None  # which index to query; None = default
        evidence_types: Optional[list[str]] = None  # restrict to these types; None = all
        source_ids: Optional[list[str]] = None  # restrict to these books; None/[] = all
        min_confidence: Optional[str] = None  # floor: unverified|low|medium|high

    class LectureBody(_BaseModel):
        topic: str = ""
        depth: Optional[int] = None
        embedder: Optional[str] = None
        source_ids: Optional[list[str]] = None

    class CompareBody(_BaseModel):
        question: str = ""
        sources: Optional[list[str]] = None  # books to compare, one column each
        k: Optional[int] = None
        embedder: Optional[str] = None
        evidence_types: Optional[list[str]] = None
        min_confidence: Optional[str] = None

except ImportError:  # pragma: no cover - only without the web extra
    AskBody = None  # type: ignore
    LectureBody = None  # type: ignore
    CompareBody = None  # type: ignore


# The compare view runs one retrieval per selected book; cap the fan-out.
MAX_COMPARE_SOURCES = 6


class EmbedderUnavailable(RuntimeError):
    """A configured embedder could not be built (e.g. semantic model unreachable)."""


@dataclass
class AppConfig:
    """How to build the retrieval + generation stack behind the web app."""

    knowledge_dir: Path = DEFAULT_KNOWLEDGE_DIR
    registry_path: Path = DEFAULT_REGISTRY
    embedders: list[str] = field(default_factory=lambda: ["tfidf"])
    synthesize: str = "none"
    judge: str = "lexical"
    decompose: str = "none"
    default_k: int = 6

    @property
    def default_embedder(self) -> str:
        return self.embedders[0]


@dataclass
class Engine:
    """The two generators bound to one embedder's index."""

    answers: AnswerGenerator
    lectures: LectureGenerator


class Stack:
    """Holds the corpus and builds a per-embedder :class:`Engine` on demand.

    Each embedder needs its *own* index (the vectors differ), so switching
    embedders means querying a different retriever. Indexes are built lazily and
    cached: the default embedder is built eagerly (validating the corpus at
    startup); any additional configured embedder is built the first time it is
    requested, and a build failure (e.g. an unreachable semantic model) is cached
    and surfaced as :class:`EmbedderUnavailable` rather than retried or crashed.
    """

    def __init__(
        self,
        docs: list[Document],
        config: AppConfig,
        known: Optional[set[str]] = None,
        sources_meta: Optional[dict[str, Source]] = None,
    ) -> None:
        self.docs = docs
        self.config = config
        self.known = known
        self.sources_meta = sources_meta or {}
        # Providers are index-independent, so build them once and share.
        self._synthesizer = make_synthesizer(config.synthesize)
        self._judge = make_judge(config.judge)
        self._decomposer = make_decomposer(config.decompose)
        self._engines: dict[str, Engine] = {}
        self._errors: dict[str, str] = {}
        self._facets: Optional[dict] = None

    @property
    def n_documents(self) -> int:
        return len(self.docs)

    def facets(self) -> dict:
        """What's actually in this corpus: source books and evidence types.

        Powers the UI filter panel. Computed once from the loaded documents
        (joined with registry titles/confidence) and cached.
        """
        if self._facets is not None:
            return self._facets
        from collections import Counter

        src_count: Counter = Counter()
        type_count: Counter = Counter()
        src_types: dict[str, set[str]] = {}
        for d in self.docs:
            sid = d.citation.source_id
            src_count[sid] += 1
            type_count[d.evidence_type.value] += 1
            src_types.setdefault(sid, set()).add(d.evidence_type.value)

        sources = []
        for sid, n in src_count.most_common():
            meta = self.sources_meta.get(sid)
            sources.append({
                "id": sid,
                "title": meta.title if meta else sid,
                "confidence": meta.confidence.value if meta else None,
                "count": n,
                "evidence_types": sorted(src_types.get(sid, ())),
            })
        self._facets = {
            "sources": sources,
            "evidence_types": [{"type": t, "count": n} for t, n in type_count.most_common()],
        }
        return self._facets

    @property
    def embedders(self) -> list[str]:
        return list(self.config.embedders)

    @property
    def default_embedder(self) -> str:
        return self.config.default_embedder

    def embedder_state(self, spec: str) -> str:
        """``ready`` (built), ``failed`` (build errored), or ``lazy`` (not yet built)."""
        if spec in self._engines:
            return "ready"
        if spec in self._errors:
            return "failed"
        return "lazy"

    def error_for(self, spec: str) -> Optional[str]:
        return self._errors.get(spec)

    def engine(self, spec: Optional[str] = None) -> Engine:
        """Return the Engine for ``spec`` (default embedder if None), building it once."""
        spec = spec or self.default_embedder
        if spec not in self.config.embedders:
            raise EmbedderUnavailable(
                f"Embedder {spec!r} is not enabled. Available: "
                + ", ".join(self.config.embedders)
            )
        if spec in self._engines:
            return self._engines[spec]
        if spec in self._errors:
            raise EmbedderUnavailable(self._errors[spec])
        try:
            retriever = build_index(self.docs, embedder=make_embedder(spec))
        except Exception as exc:  # noqa: BLE001 - report, don't crash the server
            self._errors[spec] = str(exc)
            raise EmbedderUnavailable(str(exc)) from exc
        engine = Engine(
            answers=AnswerGenerator(
                retriever,
                synthesizer=self._synthesizer,
                known_source_ids=self.known,
                judge=self._judge,
                decomposer=self._decomposer,
            ),
            lectures=LectureGenerator(
                retriever, synthesizer=self._synthesizer, judge=self._judge
            ),
        )
        self._engines[spec] = engine
        return engine


def build_stack(config: Optional[AppConfig] = None) -> Stack:
    """Load the corpus and prepare the generators (default index built eagerly).

    Pure pipeline code — no web dependency — so it is unit-testable on its own
    and reused by both the API and any embedded use.
    """
    config = config or AppConfig()
    docs = list(iter_knowledge_dir(config.knowledge_dir))
    if not docs:
        raise RuntimeError(
            f"No documents found under {config.knowledge_dir}. Build the corpus "
            "first (python scripts/ingest.py) or point --knowledge-dir at a "
            "directory of .jsonl knowledge files."
        )
    known = _load_known_ids(config.registry_path)
    sources_meta = _load_sources_meta(config.registry_path)
    stack = Stack(docs, config, known, sources_meta)
    stack.engine(config.default_embedder)  # eager: validate corpus + default index
    return stack


def _load_known_ids(registry_path: Path) -> Optional[set[str]]:
    try:
        return load_registry_ids(registry_path)
    except FileNotFoundError:
        return None


def _load_sources_meta(registry_path: Path) -> dict[str, Source]:
    try:
        return {s.id: s for s in load_sources(registry_path)}
    except FileNotFoundError:
        return {}


# ---------------------------------------------------------------------------
# JSON payload builders (structured, so the browser can render badges itself)
# ---------------------------------------------------------------------------


def answer_to_payload(answer: Answer, markdown: str) -> dict:
    return {"answer": answer.to_dict(), "markdown": markdown}


def lecture_to_payload(lecture: Lecture) -> dict:
    return {
        "topic": lecture.topic,
        "generated_on": lecture.generated_on,
        "sections": [
            {
                "title": s.title,
                "body": s.body,
                "synthesized": s.synthesized,
                "note": s.note or "",
                "evidence": [
                    {
                        "text": r.document.text.strip(),
                        "reference": r.document.citation.reference_string(),
                        "confidence": r.document.confidence.value,
                        "evidence_type": r.document.evidence_type.value,
                        "translation": r.document.citation.translation,
                        "view_status": r.document.view_status.value if r.document.view_status else None,
                        "citation": r.document.citation.to_dict(),
                    }
                    for r in s.evidence
                ],
            }
            for s in lecture.sections
        ],
        "markdown": lecture.to_markdown(),
    }


# ---------------------------------------------------------------------------
# FastAPI app
# ---------------------------------------------------------------------------


def create_app(config: Optional[AppConfig] = None, *, stack: Optional[Stack] = None):
    """Build the FastAPI application.

    ``stack`` lets tests inject a pre-built (small-corpus) stack; otherwise it is
    built from ``config`` at creation time. Raises a clear ImportError with an
    install hint if FastAPI isn't available.
    """
    try:
        from fastapi import FastAPI
        from fastapi.responses import HTMLResponse, JSONResponse
    except ImportError as exc:  # pragma: no cover - exercised only without the extra
        raise ImportError(_FASTAPI_HINT) from exc

    stack = stack or build_stack(config)

    app = FastAPI(
        title="Shia-Aalim",
        description="Evidence-first Twelver Shia research & lecture assistant. "
        "No citation = not a fact.",
        version="0.1.0",
    )
    app.state.stack = stack

    @app.get("/", response_class=HTMLResponse)
    async def index() -> str:
        return INDEX_HTML

    @app.get("/api/status")
    async def status() -> dict:
        cfg = stack.config
        return {
            "documents": stack.n_documents,
            "embedders": [
                {"spec": spec, "state": stack.embedder_state(spec),
                 "default": spec == stack.default_embedder}
                for spec in stack.embedders
            ],
            "default_embedder": stack.default_embedder,
            "synthesizer": cfg.synthesize,
            "judge": cfg.judge,
            "decomposer": cfg.decompose,
            "default_k": cfg.default_k,
        }

    @app.get("/api/sources")
    async def sources() -> dict:
        return stack.facets()

    @app.post("/api/answer")
    async def api_answer(body: AskBody):
        question = (body.question or "").strip()
        if not question:
            return JSONResponse({"error": "question is required"}, status_code=400)
        try:
            engine = stack.engine(body.embedder)
        except EmbedderUnavailable as exc:
            return JSONResponse({"error": _embedder_error(body.embedder, exc)}, status_code=503)
        k = _clamp_int(body.k, default=stack.config.default_k, lo=1, hi=25)
        answer = engine.answers.answer(
            question,
            k=k,
            evidence_types=_parse_types(body.evidence_types),
            source_ids=_parse_sources(body.source_ids),
            min_confidence=_parse_confidence(body.min_confidence),
        )
        markdown = engine.answers.format_markdown(answer)
        payload = answer_to_payload(answer, markdown)
        payload["embedder"] = body.embedder or stack.default_embedder
        return payload

    @app.post("/api/lecture")
    async def api_lecture(body: LectureBody):
        topic = (body.topic or "").strip()
        if not topic:
            return JSONResponse({"error": "topic is required"}, status_code=400)
        try:
            engine = stack.engine(body.embedder)
        except EmbedderUnavailable as exc:
            return JSONResponse({"error": _embedder_error(body.embedder, exc)}, status_code=503)
        depth = _clamp_int(body.depth, default=4, lo=1, hi=10)
        lecture = engine.lectures.generate(
            topic, depth=depth, source_ids=_parse_sources(body.source_ids)
        )
        payload = lecture_to_payload(lecture)
        payload["embedder"] = body.embedder or stack.default_embedder
        return payload

    @app.post("/api/compare")
    async def api_compare(body: CompareBody):
        question = (body.question or "").strip()
        if not question:
            return JSONResponse({"error": "question is required"}, status_code=400)
        sources = [s for s in (body.sources or []) if s]
        if not sources:
            return JSONResponse({"error": "select at least one book to compare"}, status_code=400)
        try:
            engine = stack.engine(body.embedder)
        except EmbedderUnavailable as exc:
            return JSONResponse({"error": _embedder_error(body.embedder, exc)}, status_code=503)

        truncated = len(sources) > MAX_COMPARE_SOURCES
        sources = sources[:MAX_COMPARE_SOURCES]
        k = _clamp_int(body.k, default=4, lo=1, hi=15)
        types = _parse_types(body.evidence_types)
        conf = _parse_confidence(body.min_confidence)
        titles = {s["id"]: s["title"] for s in stack.facets()["sources"]}

        columns = []
        for sid in sources:
            # Same question, each book answered on its own evidence only.
            ans = engine.answers.answer(
                question, k=k, evidence_types=types, source_ids={sid}, min_confidence=conf
            )
            columns.append({
                "source_id": sid,
                "title": titles.get(sid, sid),
                "answer": ans.to_dict(),
                "markdown": engine.answers.format_markdown(ans),
            })
        return {
            "question": question,
            "embedder": body.embedder or stack.default_embedder,
            "columns": columns,
            "truncated": truncated,
        }

    return app


def _parse_types(values: Optional[list[str]]) -> Optional[list[EvidenceType]]:
    """Turn incoming strings into EvidenceType values; unknown ones are dropped."""
    if not values:
        return None
    out: list[EvidenceType] = []
    for v in values:
        try:
            out.append(EvidenceType(v))
        except ValueError:
            continue
    return out or None


def _parse_sources(values: Optional[list[str]]) -> Optional[set[str]]:
    if not values:
        return None
    picked = {v for v in values if v}
    return picked or None


def _parse_confidence(value: Optional[str]) -> ConfidenceLevel:
    """Map a floor string to a ConfidenceLevel; default LOW (the generator default)."""
    if not value:
        return ConfidenceLevel.LOW
    try:
        return ConfidenceLevel(value)
    except ValueError:
        return ConfidenceLevel.LOW


def _embedder_error(spec: Optional[str], exc: Exception) -> str:
    return (
        f"The '{spec}' embedder is not available in this environment: {exc}. "
        "Semantic models (st:…) need the [embeddings] extra and a reachable "
        "model; switch back to the tfidf index."
    )


def _clamp_int(value, *, default: int, lo: int, hi: int) -> int:
    try:
        n = int(value)
    except (TypeError, ValueError):
        return default
    return max(lo, min(hi, n))


# ---------------------------------------------------------------------------
# Single-page UI — self-contained (no external assets), so it works offline.
# ---------------------------------------------------------------------------

INDEX_HTML = r"""<!doctype html>
<html lang="en">
<head>
<meta charset="utf-8">
<meta name="viewport" content="width=device-width, initial-scale=1">
<title>Shia-Aalim — evidence-first research assistant</title>
<style>
  :root {
    --bg: #0f1114; --panel: #171a1f; --panel2: #1e232a; --line: #2a3038;
    --ink: #e7ecf2; --muted: #93a1b0; --accent: #3f8cff; --accent2: #2b6fd6;
    --high: #2ea043; --medium: #d29922; --low: #db6d28; --unverified: #6e7681;
    --quran: #7c5cff; --hadith: #2ea3a3; --tafsir: #c46fd6;
    --historical: #d2792a; --scholarly: #4b8ef0;
  }
  @media (prefers-color-scheme: light) {
    :root {
      --bg: #f5f7fa; --panel: #ffffff; --panel2: #eef1f5; --line: #dde3ea;
      --ink: #10151c; --muted: #5a6672; --accent: #1f6feb; --accent2: #1a5fd0;
    }
  }
  * { box-sizing: border-box; }
  body {
    margin: 0; background: var(--bg); color: var(--ink);
    font: 15px/1.55 -apple-system, BlinkMacSystemFont, "Segoe UI", Roboto, Helvetica, Arial, sans-serif;
  }
  header {
    padding: 20px 22px; border-bottom: 1px solid var(--line);
    background: var(--panel); position: sticky; top: 0; z-index: 5;
  }
  header h1 { margin: 0; font-size: 20px; letter-spacing: .2px; }
  header .tag { color: var(--muted); font-size: 13px; margin-top: 3px; }
  header .tag b { color: var(--accent); }
  main { max-width: 900px; margin: 0 auto; padding: 22px 18px 80px; }
  .tabs { display: flex; gap: 8px; margin-bottom: 18px; }
  .tab {
    padding: 8px 16px; border: 1px solid var(--line); border-radius: 999px;
    background: var(--panel); color: var(--muted); cursor: pointer; font-size: 14px;
  }
  .tab.active { background: var(--accent); border-color: var(--accent); color: #fff; }
  .row { display: flex; gap: 10px; flex-wrap: wrap; }
  input[type=text] {
    flex: 1 1 320px; padding: 12px 14px; border-radius: 10px;
    border: 1px solid var(--line); background: var(--panel); color: var(--ink); font-size: 15px;
  }
  input[type=number] {
    width: 88px; padding: 12px 10px; border-radius: 10px;
    border: 1px solid var(--line); background: var(--panel); color: var(--ink); font-size: 15px;
  }
  button.go {
    padding: 12px 20px; border: 0; border-radius: 10px; cursor: pointer;
    background: var(--accent); color: #fff; font-size: 15px; font-weight: 600;
  }
  button.go:disabled { opacity: .5; cursor: default; }
  label.fld { display: flex; flex-direction: column; gap: 4px; font-size: 12px; color: var(--muted); }
  .hint { color: var(--muted); font-size: 13px; margin: 10px 2px 0; }
  .status { color: var(--muted); font-size: 12.5px; margin-top: 14px; }
  .result { margin-top: 22px; }
  .qtitle { font-size: 18px; font-weight: 650; margin: 0 0 6px; }
  .subq { color: var(--muted); font-size: 13px; margin: 0 0 14px; }
  .summary {
    background: var(--panel2); border: 1px solid var(--line); border-left: 3px solid var(--accent);
    padding: 12px 14px; border-radius: 8px; margin: 0 0 18px; white-space: pre-wrap;
  }
  .summary .lbl { color: var(--muted); font-size: 12px; margin-bottom: 6px; }
  .evhead { font-size: 13px; text-transform: uppercase; letter-spacing: .6px; color: var(--muted); margin: 18px 0 8px; }
  .ev {
    background: var(--panel); border: 1px solid var(--line); border-radius: 10px;
    padding: 12px 14px; margin-bottom: 10px;
  }
  .ev .txt { margin: 0 0 8px; }
  .ev .ar { direction: rtl; text-align: right; font-size: 17px; line-height: 1.9; }
  .badges { display: flex; gap: 6px; flex-wrap: wrap; align-items: center; }
  .badge {
    font-size: 11px; font-weight: 700; text-transform: uppercase; letter-spacing: .4px;
    padding: 2px 8px; border-radius: 999px; color: #fff;
  }
  .ref { color: var(--muted); font-size: 12.5px; margin-left: auto; font-variant-numeric: tabular-nums; }
  .b-high { background: var(--high); } .b-medium { background: var(--medium); }
  .b-low { background: var(--low); } .b-unverified { background: var(--unverified); }
  .t-quran { background: var(--quran); } .t-hadith { background: var(--hadith); }
  .t-tafsir { background: var(--tafsir); } .t-historical { background: var(--historical); }
  .t-scholarly_opinion { background: var(--scholarly); } .t-biographical { background: #8a7a5c; }
  .t-linguistic { background: #5c8a7a; } .t-historical { background: var(--historical); }
  .caveats { margin-top: 20px; border-top: 1px dashed var(--line); padding-top: 14px; }
  .caveats .lbl { color: var(--low); font-size: 12px; text-transform: uppercase; letter-spacing: .5px; }
  .caveats ul { margin: 8px 0 0; padding-left: 18px; }
  .caveats li { color: var(--muted); font-size: 13px; margin-bottom: 5px; }
  .sec { margin-bottom: 22px; }
  .sec h3 { margin: 0 0 4px; font-size: 16px; }
  .sec .note { color: var(--muted); font-size: 13px; font-style: italic; margin: 2px 0 8px; }
  .sec .body { white-space: pre-wrap; margin: 6px 0 10px; }
  .synth { color: var(--high); font-size: 12px; font-weight: 600; }
  .empty { color: var(--muted); padding: 20px 0; }
  .cols { display: flex; gap: 14px; overflow-x: auto; padding-bottom: 10px; }
  .col { flex: 0 0 320px; max-width: 360px; border: 1px solid var(--line); border-radius: 10px; padding: 12px 12px 4px; background: var(--panel2); }
  .col h4 { margin: 0 0 2px; font-size: 14.5px; }
  .col .meta { color: var(--muted); font-size: 12px; margin-bottom: 10px; }
  .col .ev { background: var(--panel); }
  .col .empty { padding: 6px 0 12px; font-size: 13px; }
  .spinner { color: var(--muted); padding: 20px 0; }
  .spinner.building { color: var(--medium); }
  .spinner.building code { color: var(--ink); }
  .spinner::after { content: ""; animation: dots 1.2s steps(4,end) infinite; }
  @keyframes dots { 0%{content:""} 25%{content:"·"} 50%{content:"··"} 75%{content:"···"} }
  footer { color: var(--muted); font-size: 12px; text-align: center; padding: 30px 0 10px; }
  code { background: var(--panel2); padding: 1px 5px; border-radius: 4px; font-size: 12.5px; }
  select {
    padding: 11px 12px; border-radius: 10px; border: 1px solid var(--line);
    background: var(--panel); color: var(--ink); font-size: 14px;
  }
  select:disabled { opacity: .6; }
  .toolbar { display: flex; gap: 8px; margin: 4px 0 14px; }
  .toolbar.hidden { display: none; }
  button.mini {
    padding: 6px 12px; border: 1px solid var(--line); border-radius: 8px; cursor: pointer;
    background: var(--panel); color: var(--ink); font-size: 12.5px;
  }
  button.mini:hover { border-color: var(--accent); color: var(--accent); }
  .idxrow { display: flex; align-items: center; gap: 8px; margin-bottom: 14px; color: var(--muted); font-size: 13px; }
  .idxnote { font-size: 12px; color: var(--muted); }
  details.filters {
    border: 1px solid var(--line); border-radius: 10px; background: var(--panel);
    padding: 0 14px; margin: 10px 0 4px;
  }
  details.filters summary {
    cursor: pointer; padding: 11px 0; font-size: 13.5px; color: var(--muted); user-select: none;
  }
  details.filters[open] summary { border-bottom: 1px solid var(--line); margin-bottom: 12px; }
  .filters .active-count { color: var(--accent); font-weight: 600; }
  .fgrid { display: flex; gap: 22px; flex-wrap: wrap; margin-bottom: 12px; }
  .fcol { min-width: 180px; }
  .flabel { font-size: 12px; text-transform: uppercase; letter-spacing: .5px; color: var(--muted); margin: 6px 0 8px; }
  .checks { display: flex; flex-direction: column; gap: 6px; }
  .srclist { max-height: 220px; overflow-y: auto; padding: 4px 6px 4px 2px; border: 1px solid var(--line); border-radius: 8px; }
  label.chk { display: flex; align-items: center; gap: 8px; font-size: 13.5px; cursor: pointer; padding: 1px 0; }
  label.chk input { accent-color: var(--accent); }
  label.chk .cnt { color: var(--muted); font-size: 12px; margin-left: auto; font-variant-numeric: tabular-nums; }
  label.chk .cdot { width: 8px; height: 8px; border-radius: 50%; display: inline-block; flex: none; }
  .srcsearch { width: 100%; padding: 8px 10px; margin-bottom: 8px; border-radius: 8px; border: 1px solid var(--line); background: var(--panel2); color: var(--ink); font-size: 13px; }
  .frow { display: flex; gap: 8px; margin-top: 8px; align-items: center; }
  .fmini { padding: 4px 10px; border: 1px solid var(--line); border-radius: 7px; background: var(--panel); color: var(--muted); cursor: pointer; font-size: 12px; }
  .fmini:hover { border-color: var(--accent); color: var(--accent); }
  .cdot-high { background: var(--high); } .cdot-medium { background: var(--medium); }
  .cdot-low { background: var(--low); } .cdot-unverified { background: var(--unverified); }
  .ev.clickable { cursor: pointer; transition: border-color .12s; }
  .ev.clickable:hover { border-color: var(--accent); }
  .ev .more { color: var(--accent); font-size: 12px; margin-left: 8px; white-space: nowrap; }
  #drawerOverlay {
    position: fixed; inset: 0; background: rgba(0,0,0,.45); opacity: 0; pointer-events: none;
    transition: opacity .18s; z-index: 20;
  }
  #drawerOverlay.open { opacity: 1; pointer-events: auto; }
  #drawer {
    position: fixed; top: 0; right: 0; height: 100%; width: min(460px, 92vw);
    background: var(--panel); border-left: 1px solid var(--line); z-index: 21;
    transform: translateX(100%); transition: transform .2s ease; overflow-y: auto;
    box-shadow: -12px 0 40px rgba(0,0,0,.25);
  }
  #drawer.open { transform: translateX(0); }
  .drawer-head { display: flex; align-items: flex-start; gap: 10px; padding: 18px 18px 12px; border-bottom: 1px solid var(--line); position: sticky; top: 0; background: var(--panel); }
  .drawer-head h2 { margin: 0; font-size: 16px; line-height: 1.35; flex: 1; }
  .drawer-close { border: 0; background: var(--panel2); color: var(--ink); border-radius: 8px; width: 30px; height: 30px; font-size: 18px; cursor: pointer; flex: none; }
  .drawer-body { padding: 16px 18px 40px; }
  .drawer-body .ar { direction: rtl; text-align: right; font-size: 20px; line-height: 2.05; margin: 4px 0 14px; }
  .drawer-body .en { font-size: 15px; line-height: 1.65; margin: 0 0 14px; }
  .drawer-body .grp { margin: 14px 0; }
  .drawer-body .k { font-size: 11px; text-transform: uppercase; letter-spacing: .5px; color: var(--muted); }
  .drawer-body .v { font-size: 14px; margin-top: 2px; }
  .kv { display: grid; grid-template-columns: auto 1fr; gap: 4px 14px; font-size: 13.5px; }
  .kv .k { align-self: center; }
  .drawer-body .src { color: var(--muted); font-size: 13px; }
</style>
</head>
<body>
<header>
  <h1>Shia-Aalim</h1>
  <div class="tag">Evidence-first Twelver (Ithnā ʿAsharī) research &amp; lecture assistant · <b>No citation = not a fact.</b></div>
</header>
<main>
  <div class="tabs">
    <div class="tab active" data-tab="ask" onclick="switchTab('ask')">Ask a question</div>
    <div class="tab" data-tab="lecture" onclick="switchTab('lecture')">Prepare a lecture</div>
    <div class="tab" data-tab="compare" onclick="switchTab('compare')">Compare sources</div>
  </div>

  <div class="idxrow">
    <label for="embedder">Retrieval index</label>
    <select id="embedder" disabled onchange="onEmbedderChange()"><option>loading…</option></select>
    <span class="idxnote" id="idxnote"></span>
  </div>

  <section id="pane-ask">
    <div class="row">
      <input type="text" id="q" placeholder="e.g. What does the Qur'an say about justice?" onkeydown="if(event.key==='Enter')ask()">
      <label class="fld">evidence<input type="number" id="k" value="6" min="1" max="25"></label>
      <button class="go" id="askBtn" onclick="ask()">Ask</button>
    </div>
    <details class="filters" id="askFilters">
      <summary>Filters <span class="active-count" id="askFilterCount"></span></summary>
      <div class="fgrid">
        <div class="fcol">
          <div class="flabel">Evidence type</div>
          <div class="checks" id="askTypes"><span class="idxnote">loading…</span></div>
        </div>
        <div class="fcol">
          <div class="flabel">Minimum confidence</div>
          <select id="askConf" onchange="updateFilterCount('ask')">
            <option value="unverified">Any</option>
            <option value="low" selected>Low and up</option>
            <option value="medium">Medium and up</option>
            <option value="high">High only</option>
          </select>
        </div>
      </div>
      <div class="fcol" style="min-width:100%">
        <div class="flabel">Restrict to sources <span class="idxnote">(none checked = search all)</span></div>
        <input type="text" class="srcsearch" placeholder="filter this list…" oninput="filterSrcList('ask', this.value)">
        <div class="checks srclist" id="askSources"></div>
        <div class="frow">
          <button class="fmini" type="button" onclick="setAllSrc('ask', true)">Select all</button>
          <button class="fmini" type="button" onclick="setAllSrc('ask', false)">Clear</button>
        </div>
      </div>
    </details>
    <div class="hint">Every answer is grounded in retrieved, cited passages. Weak or disputed evidence is flagged, never hidden.</div>
    <div class="toolbar hidden" id="askTools">
      <button class="mini" onclick="copyMd('ask')">⧉ Copy Markdown</button>
      <button class="mini" onclick="downloadMd('ask')">⭳ Download .md</button>
    </div>
    <div class="result" id="askResult"></div>
  </section>

  <section id="pane-lecture" style="display:none">
    <div class="row">
      <input type="text" id="topic" placeholder="e.g. The patience (ṣabr) of Imam Husayn (a)" onkeydown="if(event.key==='Enter')lecture()">
      <label class="fld">depth<input type="number" id="depth" value="4" min="1" max="10"></label>
      <button class="go" id="lecBtn" onclick="lecture()">Build outline</button>
    </div>
    <details class="filters" id="lecFilters">
      <summary>Restrict to sources <span class="active-count" id="lecFilterCount"></span></summary>
      <input type="text" class="srcsearch" placeholder="filter this list…" oninput="filterSrcList('lec', this.value)">
      <div class="checks srclist" id="lecSources"></div>
      <div class="frow">
        <button class="fmini" type="button" onclick="setAllSrc('lec', true)">Select all</button>
        <button class="fmini" type="button" onclick="setAllSrc('lec', false)">Clear</button>
      </div>
    </details>
    <div class="hint">Builds the 11-section majlis/khutbah framework. Evidence sections are filled from cited passages; narrative sections are LLM-written only when a synthesizer is enabled and the prose verifies against the evidence.</div>
    <div class="toolbar hidden" id="lecTools">
      <button class="mini" onclick="copyMd('lec')">⧉ Copy Markdown</button>
      <button class="mini" onclick="downloadMd('lec')">⭳ Download .md</button>
    </div>
    <div class="result" id="lecResult"></div>
  </section>

  <section id="pane-compare" style="display:none">
    <div class="row">
      <input type="text" id="cq" placeholder="e.g. the status of the Ahl al-Bayt (a)" onkeydown="if(event.key==='Enter')compare()">
      <label class="fld">per book<input type="number" id="ck" value="4" min="1" max="15"></label>
      <button class="go" id="cmpBtn" onclick="compare()">Compare</button>
    </div>
    <div class="fcol" style="margin:10px 0">
      <div class="flabel">Books to compare <span class="active-count" id="cmpFilterCount"></span> <span class="idxnote">pick 2+ (up to 6)</span></div>
      <input type="text" class="srcsearch" placeholder="filter this list…" oninput="filterSrcList('cmp', this.value)">
      <div class="checks srclist" id="cmpSources"></div>
      <div class="frow">
        <button class="fmini" type="button" onclick="setAllSrc('cmp', true)">Select all</button>
        <button class="fmini" type="button" onclick="setAllSrc('cmp', false)">Clear</button>
      </div>
    </div>
    <div class="hint">Runs the same question separately against each selected book and lines the answers up side by side — so you can see which books actually speak to it, and how.</div>
    <div class="toolbar hidden" id="cmpTools">
      <button class="mini" onclick="copyMd('cmp')">⧉ Copy Markdown</button>
      <button class="mini" onclick="downloadMd('cmp')">⭳ Download .md</button>
    </div>
    <div class="result" id="cmpResult"></div>
  </section>

  <div class="status" id="status">Loading corpus status…</div>
</main>
<footer>Shia-Aalim · answers are aids to research, not a substitute for a qualified scholar (marjaʿ). Verify every citation against the primary source.</footer>

<div id="drawerOverlay" onclick="closeDrawer()"></div>
<aside id="drawer" aria-hidden="true">
  <div class="drawer-head">
    <h2 id="drawerTitle"></h2>
    <button class="drawer-close" onclick="closeDrawer()" aria-label="Close">×</button>
  </div>
  <div class="drawer-body" id="drawerBody"></div>
</aside>

<script>
function esc(s){ return (s==null?'':String(s)).replace(/[&<>"']/g, c => ({'&':'&amp;','<':'&lt;','>':'&gt;','"':'&quot;',"'":'&#39;'}[c])); }
function isArabic(s){ return /[؀-ۿ]/.test(s||''); }

function switchTab(name){
  document.querySelectorAll('.tab').forEach(t => t.classList.toggle('active', t.dataset.tab===name));
  ['ask','lecture','compare','history'].forEach(function(p){
    var el = document.getElementById('pane-'+p);
    if(el) el.style.display = (p===name) ? '' : 'none';
  });
}

function badge(kind, cls, label){ return '<span class="badge '+cls+'-'+kind+'">'+esc(label)+'</span>'; }

// ---- Citation detail drawer ----------------------------------------------
var drawerReg = {}, drawerSeq = 0;
function regDrawer(d){ var id = 'd'+(drawerSeq++); drawerReg[id] = d; return id; }

// A unified evidence "detail" from an answer claim or a lecture evidence item.
function detailFromClaim(c){
  var cit = (c.citations && c.citations[0]) || {};
  return {
    text: c.statement, arabic: cit.arabic_text || '',
    translation: cit.translation || '', translation_source: cit.translation_source || '',
    reference: refString(cit), confidence: c.confidence, evidence_type: c.evidence_type,
    view_status: c.view_status || null, grade: cit.grade || 'ungraded',
    grade_source: cit.grade_source || '', source_id: cit.source_id, locators: cit,
    asserted_as_fact: c.asserted_as_fact,
  };
}
function detailFromEv(ev){
  var cit = ev.citation || {};
  return {
    text: ev.text, arabic: cit.arabic_text || '',
    translation: ev.translation || cit.translation || '', translation_source: cit.translation_source || '',
    reference: ev.reference || refString(cit), confidence: ev.confidence, evidence_type: ev.evidence_type,
    view_status: ev.view_status || null, grade: cit.grade || 'ungraded',
    grade_source: cit.grade_source || '', source_id: cit.source_id, locators: cit,
  };
}

function evidenceBlock(d){
  var conf = d.confidence || 'unverified';
  var type = d.evidence_type || '';
  var txt = d.text || d.arabic || '';
  var cls = isArabic(txt) ? 'txt ar' : 'txt';
  var trans = (d.translation && d.translation !== txt)
    ? '<p class="txt" style="color:var(--muted);font-size:13.5px">'+esc(d.translation)+'</p>' : '';
  var id = regDrawer(d);
  return '<div class="ev clickable" data-d="'+id+'" onclick="openDrawer(drawerReg[this.dataset.d])" '+
    'title="View full passage &amp; source details"><p class="'+cls+'">'+esc(txt)+'</p>'+trans+
    '<div class="badges">'+badge(type,'t',type.replace(/_/g,' '))+badge(conf,'b',conf)+
    '<span class="ref">'+esc(d.reference || '')+'<span class="more">details ›</span></span></div></div>';
}

function locatorRows(cit){
  var rows = [];
  function add(k,v){ if(v!==undefined && v!==null && v!=='') rows.push('<div class="k">'+k+'</div><div class="v">'+esc(v)+'</div>'); }
  add('Surah:Ayah', cit.surah ? cit.surah+':'+cit.ayah : '');
  add('Volume', cit.volume); add('Page', cit.page);
  add('Hadith no.', cit.hadith_number); add('Chapter', cit.chapter);
  return rows.join('');
}

function openDrawer(d){
  if(!d) return;
  var title = (sourceTitles[d.source_id] || d.source_id || 'Passage');
  document.getElementById('drawerTitle').textContent = title;
  var h = '<div class="src">'+esc(d.reference || '')+'</div>';
  h += '<div class="badges" style="margin:10px 0 4px">'+
       badge(d.evidence_type||'', 't', (d.evidence_type||'').replace(/_/g,' '))+
       badge(d.confidence||'unverified','b',d.confidence||'unverified')+
       (d.view_status ? '<span class="badge" style="background:var(--unverified)">'+esc(d.view_status.replace(/_/g,' '))+'</span>' : '')+
       '</div>';
  if(d.arabic) h += '<div class="grp"><div class="ar">'+esc(d.arabic)+'</div></div>';
  if(d.text)   h += '<div class="grp"><div class="k">Text</div><div class="en">'+esc(d.text)+'</div></div>';
  if(d.translation && d.translation !== d.text)
    h += '<div class="grp"><div class="k">Translation</div><div class="en">'+esc(d.translation)+'</div></div>';
  if(d.translation_source)
    h += '<div class="grp"><div class="k">Translation source</div><div class="v">'+esc(d.translation_source)+'</div></div>';
  if(d.grade && d.grade !== 'ungraded')
    h += '<div class="grp"><div class="k">Grade (ʿilm al-rijāl)</div><div class="v">'+esc(d.grade)+
         (d.grade_source ? ' <span class="src">— '+esc(d.grade_source)+'</span>' : '')+'</div></div>';
  var loc = locatorRows(d.locators||{});
  if(loc) h += '<div class="grp"><div class="k">Locators</div><div class="kv" style="margin-top:6px">'+loc+'</div></div>';
  if(d.asserted_as_fact !== undefined)
    h += '<div class="grp src">'+(d.asserted_as_fact
      ? 'Backed by a complete citation at fact-level confidence.'
      : 'Not asserted as established fact — treat as evidence to weigh, not a settled ruling.')+'</div>';
  h += '<div class="grp src">Verify against the primary source before relying on it.</div>';
  document.getElementById('drawerBody').innerHTML = h;
  document.getElementById('drawer').classList.add('open');
  document.getElementById('drawer').setAttribute('aria-hidden','false');
  document.getElementById('drawerOverlay').classList.add('open');
}
function closeDrawer(){
  document.getElementById('drawer').classList.remove('open');
  document.getElementById('drawer').setAttribute('aria-hidden','true');
  document.getElementById('drawerOverlay').classList.remove('open');
}
document.addEventListener('keydown', function(e){ if(e.key==='Escape') closeDrawer(); });

function refString(cit){
  if(!cit) return '';
  if(cit.evidence_type==='quran' && cit.surah) return "Qur'an "+cit.surah+':'+cit.ayah;
  var p=[cit.source_id];
  if(cit.volume) p.push('v'+cit.volume);
  if(cit.page) p.push('p.'+cit.page);
  if(cit.hadith_number) p.push('h.'+cit.hadith_number);
  if(cit.chapter) p.push('ch.'+cit.chapter);
  return p.filter(Boolean).join(', ');
}

// Last-rendered Markdown per tab, for the copy / download buttons.
var lastMd = { ask: {text:'', name:'answer'}, lec: {text:'', name:'lecture'}, cmp: {text:'', name:'compare'} };
function slug(s){ return (s||'shia-aalim').toLowerCase().replace(/[^a-z0-9]+/g,'-').replace(/^-|-$/g,'').slice(0,60) || 'shia-aalim'; }
function selectedEmbedder(){ var el = document.getElementById('embedder'); return el && el.value ? el.value : null; }
function showTools(tab){ document.getElementById(tab+'Tools').classList.remove('hidden'); }
function hideTools(tab){ document.getElementById(tab+'Tools').classList.add('hidden'); }

var embedderStates = {};   // spec -> 'ready' | 'lazy' | 'failed', from /api/status
// Choose the waiting message: an index that hasn't been built yet ('lazy') can
// take a while on a large corpus, so say so instead of a bare "Searching…".
function spinner(base){
  var spec = selectedEmbedder();
  if(spec && embedderStates[spec] === 'lazy'){
    return '<div class="spinner building">Building the <code>'+esc(spec)+
      '</code> index for the first time — on a large corpus this can take a minute. '+
      'It is cached, so later queries are fast</div>';
  }
  return '<div class="spinner">'+base+'</div>';
}

// ---- Filters (evidence type, source book, minimum confidence) -------------
function checked(containerId){
  return Array.prototype.slice.call(document.querySelectorAll('#'+containerId+' input:checked'))
    .map(function(i){ return i.value; });
}
function selectedTypes(prefix){ var v = checked(prefix+'Types'); return v.length ? v : null; }
function selectedSources(prefix){ var v = checked(prefix+'Sources'); return v.length ? v : null; }

function filterSrcList(prefix, q){
  q = (q||'').toLowerCase();
  document.querySelectorAll('#'+prefix+'Sources label.chk').forEach(function(l){
    l.style.display = l.dataset.search.indexOf(q) >= 0 ? '' : 'none';
  });
}
function setAllSrc(prefix, val){
  document.querySelectorAll('#'+prefix+'Sources label.chk').forEach(function(l){
    if(l.style.display !== 'none') l.querySelector('input').checked = val;  // only visible rows
  });
  updateFilterCount(prefix);
}
function setCount(id, txt){ var el = document.getElementById(id); if(el) el.textContent = txt; }
function updateFilterCount(prefix){
  if(prefix === 'ask'){
    var n = checked('askTypes').length + checked('askSources').length;
    var conf = document.getElementById('askConf');
    if(conf && conf.value !== 'low') n += 1;   // 'low' is the default floor
    setCount('askFilterCount', n ? '· '+n+' active' : '');
  } else {
    var m = checked(prefix+'Sources').length;
    setCount(prefix+'FilterCount', m ? '· '+m+' book'+(m>1?'s':'') : '');
  }
}

function srcRow(prefix, s){
  var dot = s.confidence ? '<span class="cdot cdot-'+esc(s.confidence)+'" title="'+esc(s.confidence)+' confidence"></span>' : '';
  var search = (s.title+' '+s.id).toLowerCase();
  return '<label class="chk" data-search="'+esc(search)+'">'+
    '<input type="checkbox" value="'+esc(s.id)+'" onchange="updateFilterCount(\''+prefix+'\')">'+
    dot+esc(s.title)+'<span class="cnt">'+s.count.toLocaleString()+'</span></label>';
}
function typeRow(t){
  var label = t.type.replace(/_/g,' ');
  return '<label class="chk"><input type="checkbox" value="'+esc(t.type)+'" onchange="updateFilterCount(\'ask\')"> '+
    esc(label)+'<span class="cnt">'+t.count.toLocaleString()+'</span></label>';
}

var sourceTitles = {};   // source_id -> human title, for the drawer header
function loadFacets(){
  return fetch('/api/sources').then(r=>r.json()).then(function(f){
    (f.sources||[]).forEach(function(s){ sourceTitles[s.id] = s.title; });
    document.getElementById('askTypes').innerHTML = (f.evidence_types||[]).map(typeRow).join('') || '<span class="idxnote">none</span>';
    var srcHtml = function(prefix){ return (f.sources||[]).map(function(s){ return srcRow(prefix, s); }).join(''); };
    document.getElementById('askSources').innerHTML = srcHtml('ask');
    document.getElementById('lecSources').innerHTML = srcHtml('lec');
    document.getElementById('cmpSources').innerHTML = srcHtml('cmp');
  }).catch(function(){
    document.getElementById('askTypes').innerHTML = '<span class="idxnote">unavailable</span>';
  });
}

async function copyMd(tab){
  var md = lastMd[tab].text; if(!md) return;
  try { await navigator.clipboard.writeText(md); flash(tab, 'Copied ✓'); }
  catch(e){
    var ta = document.createElement('textarea'); ta.value = md; document.body.appendChild(ta);
    ta.select(); try { document.execCommand('copy'); flash(tab,'Copied ✓'); } catch(_){}
    document.body.removeChild(ta);
  }
}
function downloadMd(tab){
  var md = lastMd[tab].text; if(!md) return;
  var blob = new Blob([md], {type:'text/markdown;charset=utf-8'});
  var url = URL.createObjectURL(blob);
  var a = document.createElement('a');
  a.href = url; a.download = slug(lastMd[tab].name) + '.md';
  document.body.appendChild(a); a.click(); document.body.removeChild(a);
  URL.revokeObjectURL(url);
}
function flash(tab, msg){
  var btn = document.querySelector('#'+tab+'Tools button'); if(!btn) return;
  var old = btn.textContent; btn.textContent = msg;
  setTimeout(function(){ btn.textContent = old; }, 1200);
}

async function ask(){
  var q = document.getElementById('q').value.trim();
  if(!q) return;
  var k = document.getElementById('k').value;
  var box = document.getElementById('askResult');
  var btn = document.getElementById('askBtn');
  btn.disabled = true; hideTools('ask'); box.innerHTML = spinner('Searching the corpus…');
  try {
    var res = await fetch('/api/answer', {method:'POST', headers:{'Content-Type':'application/json'}, body: JSON.stringify({
      question:q, k:Number(k), embedder:selectedEmbedder(),
      evidence_types: selectedTypes('ask'), source_ids: selectedSources('ask'),
      min_confidence: document.getElementById('askConf').value
    })});
    var data = await res.json();
    if(data.error){ box.innerHTML = '<div class="empty">'+esc(data.error)+'</div>'; return; }
    renderAnswer(box, data.answer);
    lastMd.ask = { text: data.markdown || '', name: data.answer.question };
    showTools('ask');
  } catch(e){ box.innerHTML = '<div class="empty">Request failed: '+esc(e.message)+'</div>'; }
  finally { btn.disabled = false; refreshStatus(); }
}

function renderAnswer(box, a){
  var h = '<div class="qtitle">'+esc(a.question)+'</div>';
  if(a.sub_questions && a.sub_questions.length)
    h += '<p class="subq">Decomposed into: '+a.sub_questions.map(esc).join(' · ')+'</p>';
  if(a.summary)
    h += '<div class="summary"><div class="lbl">Synthesized answer — LLM prose, verified against the evidence below</div>'+esc(a.summary)+'</div>';
  if(!a.claims || !a.claims.length){
    h += '<div class="empty">No sufficiently-relevant evidence was found in the knowledge base for this question.</div>';
  } else {
    h += '<div class="evhead">Evidence ('+a.claims.length+') · <span class="idxnote">click a passage for full text &amp; source details</span></div>';
    h += a.claims.map(c => evidenceBlock(detailFromClaim(c))).join('');
  }
  if(a.caveats && a.caveats.length)
    h += '<div class="caveats"><div class="lbl">Caveats</div><ul>'+a.caveats.map(c=>'<li>'+esc(c)+'</li>').join('')+'</ul></div>';
  box.innerHTML = h;
}

async function lecture(){
  var t = document.getElementById('topic').value.trim();
  if(!t) return;
  var depth = document.getElementById('depth').value;
  var box = document.getElementById('lecResult');
  var btn = document.getElementById('lecBtn');
  btn.disabled = true; hideTools('lec'); box.innerHTML = spinner('Building the outline…');
  try {
    var res = await fetch('/api/lecture', {method:'POST', headers:{'Content-Type':'application/json'}, body: JSON.stringify({
      topic:t, depth:Number(depth), embedder:selectedEmbedder(), source_ids: selectedSources('lec')
    })});
    var data = await res.json();
    if(data.error){ box.innerHTML = '<div class="empty">'+esc(data.error)+'</div>'; return; }
    renderLecture(box, data);
    lastMd.lec = { text: data.markdown || '', name: data.topic };
    showTools('lec');
  } catch(e){ box.innerHTML = '<div class="empty">Request failed: '+esc(e.message)+'</div>'; }
  finally { btn.disabled = false; refreshStatus(); }
}

async function compare(){
  var q = document.getElementById('cq').value.trim();
  if(!q) return;
  var sources = selectedSources('cmp');
  var box = document.getElementById('cmpResult');
  if(!sources){ box.innerHTML = '<div class="empty">Select at least one book to compare (use the list above).</div>'; return; }
  var k = document.getElementById('ck').value;
  var btn = document.getElementById('cmpBtn');
  btn.disabled = true; hideTools('cmp');
  box.innerHTML = spinner('Comparing across '+sources.length+' book'+(sources.length>1?'s':'')+'…');
  try {
    var res = await fetch('/api/compare', {method:'POST', headers:{'Content-Type':'application/json'}, body: JSON.stringify({
      question:q, sources:sources, k:Number(k), embedder:selectedEmbedder()
    })});
    var data = await res.json();
    if(data.error){ box.innerHTML = '<div class="empty">'+esc(data.error)+'</div>'; return; }
    renderCompare(box, data);
    lastMd.cmp = { text: compareMarkdown(data), name: 'compare-'+q };
    showTools('cmp');
  } catch(e){ box.innerHTML = '<div class="empty">Request failed: '+esc(e.message)+'</div>'; }
  finally { btn.disabled = false; refreshStatus(); }
}

function renderCompare(box, data){
  var h = '<div class="qtitle">'+esc(data.question)+'</div>'+
    '<p class="subq">Same question, each book answered on its own evidence. Click any passage for details.'+
    (data.truncated ? ' <b>(limited to the first 6 books)</b>' : '')+'</p>';
  h += '<div class="cols">' + (data.columns||[]).map(function(col){
    var claims = (col.answer && col.answer.claims) || [];
    var out = '<div class="col"><h4>'+esc(col.title)+'</h4>'+
      '<div class="meta">'+(claims.length ? claims.length+' passage'+(claims.length>1?'s':'') : 'no matching evidence')+'</div>';
    out += claims.length
      ? claims.map(c => evidenceBlock(detailFromClaim(c))).join('')
      : '<div class="empty">Nothing in this book cleared the bar for the question.</div>';
    return out + '</div>';
  }).join('') + '</div>';
  box.innerHTML = h;
}

function compareMarkdown(data){
  var lines = ['# Compare — '+data.question, ''];
  (data.columns||[]).forEach(function(col){
    lines.push('## '+col.title);
    var claims = (col.answer && col.answer.claims) || [];
    if(!claims.length){ lines.push('', '_No matching evidence._', ''); return; }
    lines.push('');
    claims.forEach(function(c){
      var cit = (c.citations && c.citations[0]) || {};
      lines.push('- **['+c.evidence_type+' · '+String(c.confidence).toUpperCase()+']** '+c.statement);
      lines.push('  — _'+refString(cit)+'_');
    });
    lines.push('');
  });
  return lines.join('\n');
}

function renderLecture(box, L){
  var h = '<div class="qtitle">'+esc(L.topic)+'</div><p class="subq">Outline generated '+esc(L.generated_on)+'. Verify every citation before delivery.</p>';
  h += L.sections.map(s => {
    var out = '<div class="sec"><h3>'+esc(s.title)+(s.synthesized?' <span class="synth">✓ synthesized &amp; verified</span>':'')+'</h3>';
    if(s.body) out += '<div class="body">'+esc(s.body)+'</div>';
    out += s.evidence.map(function(ev){ return evidenceBlock(detailFromEv(ev)); }).join('');
    if(s.note) out += '<div class="note">Lecturer note: '+esc(s.note)+'</div>';
    return out + '</div>';
  }).join('');
  box.innerHTML = h;
}

function stateTag(st){ return st==='ready' ? '' : st==='failed' ? ' (unavailable)' : ' — builds on first use'; }

function onEmbedderChange(){
  var el = document.getElementById('embedder');
  var st = el.options[el.selectedIndex] ? el.options[el.selectedIndex].dataset.state : 'ready';
  document.getElementById('idxnote').textContent =
    st==='lazy' ? 'This index will be built the first time you query it.' :
    st==='failed' ? 'This index failed to build in this environment; queries will report the reason.' : '';
}

function applyStatus(s){
  var sel = document.getElementById('embedder');
  var cur = sel.value;
  embedderStates = {};
  (s.embedders||[]).forEach(function(e){ embedderStates[e.spec] = e.state; });
  sel.innerHTML = (s.embedders||[]).map(function(e){
    return '<option value="'+esc(e.spec)+'" data-state="'+esc(e.state)+'"'+(e.default?' selected':'')+'>'+
      esc(e.spec)+stateTag(e.state)+'</option>';
  }).join('');
  if(cur && embedderStates[cur] !== undefined) sel.value = cur;   // keep the user's choice
  sel.disabled = (s.embedders||[]).length < 2;   // nothing to switch between
  onEmbedderChange();
  document.getElementById('status').innerHTML =
    'Corpus: <b>'+s.documents.toLocaleString()+'</b> documents · default index <code>'+esc(s.default_embedder)+
    '</code> · synthesizer <code>'+esc(s.synthesizer)+'</code> · judge <code>'+esc(s.judge)+'</code>';
}

function refreshStatus(){
  return fetch('/api/status').then(r=>r.json()).then(applyStatus)
    .catch(()=>{ document.getElementById('status').textContent = ''; });
}

refreshStatus();
loadFacets();
</script>
</body>
</html>
"""


# ---------------------------------------------------------------------------
# CLI
# ---------------------------------------------------------------------------


def main(argv: Optional[list[str]] = None) -> int:
    parser = argparse.ArgumentParser(
        description="Serve the Shia-Aalim web front-end (FastAPI + uvicorn).",
        formatter_class=argparse.RawDescriptionHelpFormatter,
    )
    parser.add_argument("--host", default="127.0.0.1")
    parser.add_argument("--port", type=int, default=8000)
    parser.add_argument("--knowledge-dir", default=str(DEFAULT_KNOWLEDGE_DIR))
    parser.add_argument("--registry", default=str(DEFAULT_REGISTRY))
    parser.add_argument(
        "--embedder", default="tfidf",
        help="one or a comma-separated list to offer as a UI toggle; the first is "
        "the default (e.g. 'tfidf' or 'tfidf,st:BAAI/bge-m3'). tfidf | hashing | st:<model>",
    )
    parser.add_argument("--synthesize", default="none", help="none | mock | claude:<model>")
    parser.add_argument("--judge", default="lexical", help="lexical | mock | claude:<model>")
    parser.add_argument("--decompose", default="none", help="none | rule | claude:<model>")
    parser.add_argument("--k", type=int, default=6, help="default evidence count per answer")
    args = parser.parse_args(argv)

    try:
        import uvicorn
    except ImportError:
        print(_FASTAPI_HINT, file=sys.stderr)
        return 1

    embedders = [s.strip() for s in args.embedder.split(",") if s.strip()] or ["tfidf"]
    config = AppConfig(
        knowledge_dir=Path(args.knowledge_dir),
        registry_path=Path(args.registry),
        embedders=embedders,
        synthesize=args.synthesize,
        judge=args.judge,
        decompose=args.decompose,
        default_k=args.k,
    )
    print(f"Loading corpus from {config.knowledge_dir} …", file=sys.stderr)
    app = create_app(config)
    n = app.state.stack.n_documents
    extra = [e for e in embedders[1:]]
    switch = f" (+{', '.join(extra)} on first use)" if extra else ""
    print(
        f"Loaded {n:,} documents; default index '{config.default_embedder}' ready{switch}. "
        f"Serving Shia-Aalim on http://{args.host}:{args.port}",
        file=sys.stderr,
    )
    uvicorn.run(app, host=args.host, port=args.port)
    return 0


if __name__ == "__main__":
    raise SystemExit(main())
